// SPDX-License-Identifier: MIT
// Copyright (c) 2026 wayland-cxx-scanner contributors
//
// xdg-simple-dmabuf-vulkan — Vulkan DMA-BUF Wayland client.
//
// Matches the visual and CLI options of Weston's simple-dmabuf-vulkan.c:
// renders a colored triangle (red/green/blue vertices) via a Vulkan graphics
// pipeline into a DMA-BUF-backed image and presents it through the
// linux-dmabuf-unstable-v1 protocol (version 3).
//
// CLI options:
//   -f, --drm-format FORMAT   DRM pixel format name (default: XRGB8888)
//   -w, --width N             window width  in pixels (default: 250)
//   -h, --height N            window height in pixels (default: 250)
//       --help                print this help and exit
//
// Rendering per frame:
//   1. Begin render pass (clear to black), bind graphics pipeline, draw the
//      3-vertex triangle, end render pass.
//   2. Submit to the graphics queue and wait on a VkFence (synchronous).
//   3. Arm a wl_surface.frame callback, attach the wl_buffer backed by the
//      DMA-BUF, damage the full surface, and commit — all in one message
//      batch to the compositor.
//
// Build requirements:
//   wayland-client, vulkan (≥ 1.1 + VK_KHR_external_memory_fd),
//   wayland-protocols (linux-dmabuf-unstable-v1), libdrm, xkbcommon.
// Runtime requirement:
//   A Wayland compositor with xdg-shell and zwp_linux_dmabuf_v1 ≥ 3.

// ── Vulkan C++ bindings
// ───────────────────────────────────────────────────────
// VULKAN_HPP_NO_EXCEPTIONS: every Vulkan call returns vk::Result /
// vk::ResultValue<T> rather than throwing; every code path is explicit.
#define VULKAN_HPP_NO_EXCEPTIONS
#include <vulkan/vulkan.hpp>

// ── Generated C++ protocol headers ───────────────────────────────────────────
// linux_dmabuf_client.hpp → namespace linux_dmabuf_unstable_v1::client
// wayland_client.hpp → namespace wayland::client
// xdg_shell_client.hpp → namespace xdg_shell::client
#include "linux_dmabuf_client.hpp"
#include "wayland_client.hpp"
#include "xdg_shell_client.hpp"

// ── System C headers
// ──────────────────────────────────────────────────────────
extern "C" {
// DRM_FORMAT_ARGB8888, DRM_FORMAT_MOD_LINEAR.
#include <drm_fourcc.h>
// KEY_ESC, WL_KEYBOARD_KEY_STATE_PRESSED.
#include <linux/input-event-codes.h>
// close().
#include <unistd.h>
// wl_*_interface symbols and WL_SEAT_CAPABILITY_KEYBOARD.
#include <wayland-client-protocol.h>
}

// ── Framework headers
// ───────────────────────────────────────────────────────── SetupHandler(),
// BindHandler(), RunEventLoop().
#include <wl/client_helpers.hpp>
// DisplayHandle, RoundtripWithTimeout().
#include <wl/display.hpp>
// CRegistry.
#include <wl/registry.hpp>
// SeatManager<App> (wl_seat + wl_keyboard + xkbcommon).
#include <wl/seat.hpp>
// WlPtr<T>.
#include <wl/wl_ptr.hpp>
// XDG interface tables + CRTP handlers.  Must follow xdg_shell_client.hpp.
#include <wl/xdg_shell.hpp>
// linux-dmabuf wl_interface tables + wl_iface() impls.  Must follow
// linux_dmabuf_client.hpp.
#include <wl/linux_dmabuf.hpp>

// ── Standard library
// ──────────────────────────────────────────────────────────
#include <algorithm>
#include <array>
#include <cerrno>
#include <cmath>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>

// ── POSIX
// ─────────────────────────────────────────────────────────────────────
#include <getopt.h>

// ══════════════════════════════════════════════════════════════════════════════
// Embedded SPIR-V shaders
//
// Generated by glslangValidator from:
//
//   // Vertex shader — rotates each vertex by pc.angle radians (push constant).
//   #version 450
//   layout(push_constant) uniform PC { float angle; } pc;
//   layout(location = 0) in vec2 in_pos;
//   layout(location = 1) in vec3 in_color;
//   layout(location = 0) out vec3 frag_color;
//   void main() {
//       float c = cos(pc.angle); float s = sin(pc.angle);
//       vec2 pos = vec2(c*in_pos.x - s*in_pos.y, s*in_pos.x + c*in_pos.y);
//       gl_Position = vec4(pos, 0.0, 1.0);
//       frag_color = in_color;
//   }
//
//   // Fragment shader
//   #version 450
//   layout(location = 0) in vec3 frag_color;
//   layout(location = 0) out vec4 out_color;
//   void main() { out_color = vec4(frag_color, 1.0); }
// ══════════════════════════════════════════════════════════════════════════════

namespace {

// clang-format off
constexpr uint32_t kVertSpv[] = {
    0x07230203u, 0x00010000u, 0x0008000bu, 0x00000045u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0009000fu, 0x00000000u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000001bu, 0x00000036u, 0x00000041u,
    0x00000043u, 0x00030003u, 0x00000002u, 0x000001c2u, 0x00040005u, 0x00000004u, 0x6e69616du, 0x00000000u,
    0x00030005u, 0x00000008u, 0x00000063u, 0x00030005u, 0x00000009u, 0x00004350u, 0x00050006u, 0x00000009u,
    0x00000000u, 0x6c676e61u, 0x00000065u, 0x00030005u, 0x0000000bu, 0x00006370u, 0x00030005u, 0x00000012u,
    0x00000073u, 0x00030005u, 0x00000018u, 0x00736f70u, 0x00040005u, 0x0000001bu, 0x705f6e69u, 0x0000736fu,
    0x00060005u, 0x00000034u, 0x505f6c67u, 0x65567265u, 0x78657472u, 0x00000000u, 0x00060006u, 0x00000034u,
    0x00000000u, 0x505f6c67u, 0x7469736fu, 0x006e6f69u, 0x00070006u, 0x00000034u, 0x00000001u, 0x505f6c67u,
    0x746e696fu, 0x657a6953u, 0x00000000u, 0x00070006u, 0x00000034u, 0x00000002u, 0x435f6c67u, 0x4470696cu,
    0x61747369u, 0x0065636eu, 0x00070006u, 0x00000034u, 0x00000003u, 0x435f6c67u, 0x446c6c75u, 0x61747369u,
    0x0065636eu, 0x00030005u, 0x00000036u, 0x00000000u, 0x00050005u, 0x00000041u, 0x67617266u, 0x6c6f635fu,
    0x0000726fu, 0x00050005u, 0x00000043u, 0x635f6e69u, 0x726f6c6fu, 0x00000000u, 0x00030047u, 0x00000009u,
    0x00000002u, 0x00050048u, 0x00000009u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040047u, 0x0000001bu,
    0x0000001eu, 0x00000000u, 0x00030047u, 0x00000034u, 0x00000002u, 0x00050048u, 0x00000034u, 0x00000000u,
    0x0000000bu, 0x00000000u, 0x00050048u, 0x00000034u, 0x00000001u, 0x0000000bu, 0x00000001u, 0x00050048u,
    0x00000034u, 0x00000002u, 0x0000000bu, 0x00000003u, 0x00050048u, 0x00000034u, 0x00000003u, 0x0000000bu,
    0x00000004u, 0x00040047u, 0x00000041u, 0x0000001eu, 0x00000000u, 0x00040047u, 0x00000043u, 0x0000001eu,
    0x00000001u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u,
    0x00000020u, 0x00040020u, 0x00000007u, 0x00000007u, 0x00000006u, 0x0003001eu, 0x00000009u, 0x00000006u,
    0x00040020u, 0x0000000au, 0x00000009u, 0x00000009u, 0x0004003bu, 0x0000000au, 0x0000000bu, 0x00000009u,
    0x00040015u, 0x0000000cu, 0x00000020u, 0x00000001u, 0x0004002bu, 0x0000000cu, 0x0000000du, 0x00000000u,
    0x00040020u, 0x0000000eu, 0x00000009u, 0x00000006u, 0x00040017u, 0x00000016u, 0x00000006u, 0x00000002u,
    0x00040020u, 0x00000017u, 0x00000007u, 0x00000016u, 0x00040020u, 0x0000001au, 0x00000001u, 0x00000016u,
    0x0004003bu, 0x0000001au, 0x0000001bu, 0x00000001u, 0x00040015u, 0x0000001cu, 0x00000020u, 0x00000000u,
    0x0004002bu, 0x0000001cu, 0x0000001du, 0x00000000u, 0x00040020u, 0x0000001eu, 0x00000001u, 0x00000006u,
    0x0004002bu, 0x0000001cu, 0x00000023u, 0x00000001u, 0x00040017u, 0x00000032u, 0x00000006u, 0x00000004u,
    0x0004001cu, 0x00000033u, 0x00000006u, 0x00000023u, 0x0006001eu, 0x00000034u, 0x00000032u, 0x00000006u,
    0x00000033u, 0x00000033u, 0x00040020u, 0x00000035u, 0x00000003u, 0x00000034u, 0x0004003bu, 0x00000035u,
    0x00000036u, 0x00000003u, 0x0004002bu, 0x00000006u, 0x00000038u, 0x00000000u, 0x0004002bu, 0x00000006u,
    0x00000039u, 0x3f800000u, 0x00040020u, 0x0000003du, 0x00000003u, 0x00000032u, 0x00040017u, 0x0000003fu,
    0x00000006u, 0x00000003u, 0x00040020u, 0x00000040u, 0x00000003u, 0x0000003fu, 0x0004003bu, 0x00000040u,
    0x00000041u, 0x00000003u, 0x00040020u, 0x00000042u, 0x00000001u, 0x0000003fu, 0x0004003bu, 0x00000042u,
    0x00000043u, 0x00000001u, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u,
    0x00000005u, 0x0004003bu, 0x00000007u, 0x00000008u, 0x00000007u, 0x0004003bu, 0x00000007u, 0x00000012u,
    0x00000007u, 0x0004003bu, 0x00000017u, 0x00000018u, 0x00000007u, 0x00050041u, 0x0000000eu, 0x0000000fu,
    0x0000000bu, 0x0000000du, 0x0004003du, 0x00000006u, 0x00000010u, 0x0000000fu, 0x0006000cu, 0x00000006u,
    0x00000011u, 0x00000001u, 0x0000000eu, 0x00000010u, 0x0003003eu, 0x00000008u, 0x00000011u, 0x00050041u,
    0x0000000eu, 0x00000013u, 0x0000000bu, 0x0000000du, 0x0004003du, 0x00000006u, 0x00000014u, 0x00000013u,
    0x0006000cu, 0x00000006u, 0x00000015u, 0x00000001u, 0x0000000du, 0x00000014u, 0x0003003eu, 0x00000012u,
    0x00000015u, 0x0004003du, 0x00000006u, 0x00000019u, 0x00000008u, 0x00050041u, 0x0000001eu, 0x0000001fu,
    0x0000001bu, 0x0000001du, 0x0004003du, 0x00000006u, 0x00000020u, 0x0000001fu, 0x00050085u, 0x00000006u,
    0x00000021u, 0x00000019u, 0x00000020u, 0x0004003du, 0x00000006u, 0x00000022u, 0x00000012u, 0x00050041u,
    0x0000001eu, 0x00000024u, 0x0000001bu, 0x00000023u, 0x0004003du, 0x00000006u, 0x00000025u, 0x00000024u,
    0x00050085u, 0x00000006u, 0x00000026u, 0x00000022u, 0x00000025u, 0x00050083u, 0x00000006u, 0x00000027u,
    0x00000021u, 0x00000026u, 0x0004003du, 0x00000006u, 0x00000028u, 0x00000012u, 0x00050041u, 0x0000001eu,
    0x00000029u, 0x0000001bu, 0x0000001du, 0x0004003du, 0x00000006u, 0x0000002au, 0x00000029u, 0x00050085u,
    0x00000006u, 0x0000002bu, 0x00000028u, 0x0000002au, 0x0004003du, 0x00000006u, 0x0000002cu, 0x00000008u,
    0x00050041u, 0x0000001eu, 0x0000002du, 0x0000001bu, 0x00000023u, 0x0004003du, 0x00000006u, 0x0000002eu,
    0x0000002du, 0x00050085u, 0x00000006u, 0x0000002fu, 0x0000002cu, 0x0000002eu, 0x00050081u, 0x00000006u,
    0x00000030u, 0x0000002bu, 0x0000002fu, 0x00050050u, 0x00000016u, 0x00000031u, 0x00000027u, 0x00000030u,
    0x0003003eu, 0x00000018u, 0x00000031u, 0x0004003du, 0x00000016u, 0x00000037u, 0x00000018u, 0x00050051u,
    0x00000006u, 0x0000003au, 0x00000037u, 0x00000000u, 0x00050051u, 0x00000006u, 0x0000003bu, 0x00000037u,
    0x00000001u, 0x00070050u, 0x00000032u, 0x0000003cu, 0x0000003au, 0x0000003bu, 0x00000038u, 0x00000039u,
    0x00050041u, 0x0000003du, 0x0000003eu, 0x00000036u, 0x0000000du, 0x0003003eu, 0x0000003eu, 0x0000003cu,
    0x0004003du, 0x0000003fu, 0x00000044u, 0x00000043u, 0x0003003eu, 0x00000041u, 0x00000044u, 0x000100fdu,
    0x00010038u,
};
constexpr uint32_t kFragSpv[] = {
    0x07230203u, 0x00010000u, 0x0008000bu, 0x00000013u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0007000fu, 0x00000004u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x00000009u, 0x0000000cu, 0x00030010u,
    0x00000004u, 0x00000007u, 0x00030003u, 0x00000002u, 0x000001c2u, 0x00040005u, 0x00000004u, 0x6e69616du,
    0x00000000u, 0x00050005u, 0x00000009u, 0x5f74756fu, 0x6f6c6f63u, 0x00000072u, 0x00050005u, 0x0000000cu,
    0x67617266u, 0x6c6f635fu, 0x0000726fu, 0x00040047u, 0x00000009u, 0x0000001eu, 0x00000000u, 0x00040047u,
    0x0000000cu, 0x0000001eu, 0x00000000u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u,
    0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u, 0x00000007u, 0x00000006u, 0x00000004u, 0x00040020u,
    0x00000008u, 0x00000003u, 0x00000007u, 0x0004003bu, 0x00000008u, 0x00000009u, 0x00000003u, 0x00040017u,
    0x0000000au, 0x00000006u, 0x00000003u, 0x00040020u, 0x0000000bu, 0x00000001u, 0x0000000au, 0x0004003bu,
    0x0000000bu, 0x0000000cu, 0x00000001u, 0x0004002bu, 0x00000006u, 0x0000000eu, 0x3f800000u, 0x00050036u,
    0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x0004003du, 0x0000000au,
    0x0000000du, 0x0000000cu, 0x00050051u, 0x00000006u, 0x0000000fu, 0x0000000du, 0x00000000u, 0x00050051u,
    0x00000006u, 0x00000010u, 0x0000000du, 0x00000001u, 0x00050051u, 0x00000006u, 0x00000011u, 0x0000000du,
    0x00000002u, 0x00070050u, 0x00000007u, 0x00000012u, 0x0000000fu, 0x00000010u, 0x00000011u, 0x0000000eu,
    0x0003003eu, 0x00000009u, 0x00000012u, 0x000100fdu, 0x00010038u,
};
// clang-format on

// Vertex layout: [x, y,  r, g, b] (vec2 position + vec3 color).
struct Vertex {
  float x, y;
  float r, g, b;
};
// The canonical Weston simple-dmabuf-vulkan triangle:
//   top: (0.0, −0.5) → red
//   bottom-left: (−0.5, 0.5) → green
//   bottom-right: (0.5, 0.5) → blue
constexpr Vertex kTriangle[3] = {
    {0.0f, -0.5f, 1.0f, 0.0f, 0.0f},
    {-0.5f, 0.5f, 0.0f, 1.0f, 0.0f},
    {0.5f, 0.5f, 0.0f, 0.0f, 1.0f},
};

// ── DRM format table
// ──────────────────────────────────────────────────────────
struct DrmFormatEntry {
  const char* name;
  uint32_t code;
};
constexpr DrmFormatEntry kDrmFormats[] = {
    {"XRGB8888", DRM_FORMAT_XRGB8888},
    {"ARGB8888", DRM_FORMAT_ARGB8888},
};

/// Return the DRM code for @p name (case-sensitive), or 0 if unknown.
uint32_t ParseDrmFormat(const char* name) noexcept {
  for (const auto& [format, code] : kDrmFormats) {
    if (std::strcmp(format, name) == 0)
      return code;
  }
  return 0;
}

}  // namespace

// ══════════════════════════════════════════════════════════════════════════════
// wl_iface() definitions — core Wayland interfaces
//
// <wayland-client-protocol.h> exposes pre-built extern const wl_interface
// symbols for every core Wayland interface.
// wl_seat_traits::wl_iface() and wl_keyboard_traits::wl_iface() are provided
// inline by <wl/seat.hpp> (already included above).
// ══════════════════════════════════════════════════════════════════════════════

namespace wayland::client {

const wl_interface& wl_callback_traits::wl_iface() noexcept {
  return wl_callback_interface;
}
const wl_interface& wl_compositor_traits::wl_iface() noexcept {
  return wl_compositor_interface;
}
const wl_interface& wl_surface_traits::wl_iface() noexcept {
  return wl_surface_interface;
}
const wl_interface& wl_buffer_traits::wl_iface() noexcept {
  return wl_buffer_interface;
}

}  // namespace wayland::client

// xdg-shell wl_interface tables and wl_iface() implementations are provided
// by <wl/xdg_shell.hpp> (already included above).
// linux-dmabuf wl_interface tables and wl_iface() implementations are
// provided by <wl/linux_dmabuf.hpp> (already included above).

// ══════════════════════════════════════════════════════════════════════════════
// Vulkan result helper
// ══════════════════════════════════════════════════════════════════════════════

namespace {

/// Log a Vulkan error to stderr and return false.  Returns true on success.
bool VkOk(vk::Result result, const char* what) noexcept {
  if (result == vk::Result::eSuccess)
    return true;
  std::fprintf(stderr, "xdg-simple-dmabuf-vulkan: %s failed (VkResult=%d)\n",
               what, static_cast<int>(result));
  return false;
}

}  // namespace

// ══════════════════════════════════════════════════════════════════════════════
// CRTP handler classes
//
// Each handler inherits the generated CRTP base and overrides only the virtual
// event methods it cares about.  Constructor requests (get_xdg_surface,
// get_toplevel, wl_surface.frame, create_params, create_immed, …) are issued
// at the call site using wl::construct<ChildTraits, Opcode>(parent, args…).
//
// wl::XdgWmBaseHandler, wl::XdgSurfaceHandler<App>, wl::XdgToplevelHandler<App>
// are provided by <wl/xdg_shell.hpp>.
// wl::SeatManager<App> (seat + keyboard) is provided by <wl/seat.hpp>.
// ══════════════════════════════════════════════════════════════════════════════

// Forward-declare App so handler callbacks can call back into it.
class App;

// ── WlCallbackHandler ────────────────────────────────────────────────────────
// Handles the one-shot wl_callback.done event emitted by the compositor to
// pace frame production.  A new instance (proxy) is allocated for every frame
// via wl_surface.frame; after done fires, the proxy is destroyed.

class WlCallbackHandler
    : public wayland::client::CWlCallback<WlCallbackHandler> {
 public:
  App* app_ = nullptr;

  void OnDone(uint32_t time_ms) override;
};

// ── WlCompositorHandler ──────────────────────────────────────────────────────
// wl_compositor has no events.  Provide the required ProcessEvent stub so the
// class is concrete.  We attach via WlPtr::Attach() rather than _SetProxy() so
// no listener table is needed.

class WlCompositorHandler
    : public wayland::client::CWlCompositor<WlCompositorHandler> {
 public:
  bool ProcessEvent(uint32_t, void**) override { return false; }
};

// ── WlSurfaceHandler ─────────────────────────────────────────────────────────
// Minimal wl_surface handler.  CWlSurface already provides Destroy() and
// default no-op overrides for enter/leave/preferred_buffer_*.

class WlSurfaceHandler : public wayland::client::CWlSurface<WlSurfaceHandler> {
};

// ── WlBufferHandler ──────────────────────────────────────────────────────────
// Tracks wl_buffer.release so we know when the compositor is done reading the
// DMA-BUF.  released_ starts true, so the very first RenderFrame() proceeds.

class WlBufferHandler : public wayland::client::CWlBuffer<WlBufferHandler> {
 public:
  bool released_ = true;
  void OnRelease() override { released_ = true; }
};

// ── LinuxDmabufHandler ───────────────────────────────────────────────────────
// Receives format/modifier advertisements from zwp_linux_dmabuf_v1 and checks
// that the compositor supports the requested DRM pixel format.

class LinuxDmabufHandler
    : public linux_dmabuf_unstable_v1::client::CZwpLinuxDmabufV1<
          LinuxDmabufHandler> {
 public:
  uint32_t desired_format = DRM_FORMAT_XRGB8888;
  bool has_format = false;

  void OnFormat(const uint32_t format) override {
    if (format == desired_format)
      has_format = true;
  }
  void OnModifier(const uint32_t format,
                  uint32_t /*mod_hi*/,
                  uint32_t /*mod_lo*/) override {
    if (format == desired_format)
      has_format = true;
  }
};

// ── LinuxBufferParamsHandler ─────────────────────────────────────────────────
// Used transiently inside CreateDmaBufBuffer() to build a wl_buffer via the
// synchronous create_immed path.  The created/failed events are not needed;
// the default no-op overrides in the generated base are enough.

class LinuxBufferParamsHandler
    : public linux_dmabuf_unstable_v1::client::CZwpLinuxBufferParamsV1<
          LinuxBufferParamsHandler> {};

// ══════════════════════════════════════════════════════════════════════════════
// App class
// ══════════════════════════════════════════════════════════════════════════════

class App {
 public:
  // CLI options parsed from argv.
  struct Options {
    uint32_t drm_format = DRM_FORMAT_XRGB8888;
    int width = 250;
    int height = 250;
  };

  explicit App(const Options opts) : opts_(opts) {}
  int Run();
  ~App();

  // ── Callbacks invoked by the CRTP handlers ──────────────────────────────
  void OnXdgSurfaceConfigure(uint32_t serial);
  void OnToplevelConfigure(int32_t w, int32_t h);
  void OnToplevelClose();
  void OnKey(uint32_t key, uint32_t state);
  /// Called by WlCallbackHandler::OnDone — render one frame and arm the next
  /// frame callback.
  void OnFrameReady(uint32_t time_ms) noexcept;

 private:
  Options opts_;

  // ── Member declaration order determines RAII destruction order.
  //    Declared first → destroyed last; declared last → destroyed first.
  //
  //    Destruction sequence (reverse of declaration order):
  //      frame_callback_ → seat_ (keyboard_ first, then seat_ inside) →
  //      xdg_toplevel_ → xdg_surface_ → xdg_wm_base_ →
  //      wl_buffer_ → linux_dmabuf_ → vk_ (VulkanState dtor) →
  //      surface_ → compositor_ → registry_ → display_

  // Wayland display — destroyed last so all proxy operations remain valid.
  wl::DisplayHandle display_;

  // Registry — destroyed before display_.
  wl::CRegistry registry_;

  // wl_compositor — no events; WlPtr::Attach() used (no s_listener_table_).
  wl::WlPtr<WlCompositorHandler> compositor_;

  // wl_surface — CWlSurface::Destroy() sends destroy request before proxy drop.
  wl::WlPtr<WlSurfaceHandler> surface_;

  // Vulkan state — declared after surface_ so VulkanState::~VulkanState() runs
  // (closing the DMA-BUF fd and releasing all Vulkan objects) before the
  // wl_surface proxy is destroyed.
  //
  // Member declaration order inside VulkanState is chosen so that
  // vk::UniqueX handles are destroyed in the correct Vulkan teardown order
  // (reverse of declaration order):
  //   fence → pipeline → framebuffer → image_view → frag_module → vert_module
  //   → pipeline_layout → render_pass → vertex_mem → vertex_buf
  //   → memory → image → cmd_buf → cmd_pool → device → instance
  struct VulkanState {
    vk::UniqueInstance instance;    // destroyed LAST (after everything)
    vk::PhysicalDevice phys_dev{};  // non-owning handle
    uint32_t queue_family = UINT32_MAX;
    vk::UniqueDevice device;                   // destroyed before instance
    vk::Queue queue{};                         // non-owning handle
    vk::UniqueCommandPool cmd_pool;            // destroyed before the device
    vk::UniqueCommandBuffer cmd_buf;           // freed before cmd_pool
    vk::UniqueImage image;                     // destroyed before the device
    vk::UniqueDeviceMemory memory;             // destroyed before the device
    vk::UniqueBuffer vertex_buf;               // destroyed before the device
    vk::UniqueDeviceMemory vertex_mem;         // destroyed before the device
    vk::UniqueRenderPass render_pass;          // destroyed before the device
    vk::UniquePipelineLayout pipeline_layout;  // destroyed before the device
    vk::UniqueShaderModule vert_module;        // destroyed before the device
    vk::UniqueShaderModule frag_module;        // destroyed before the device
    vk::UniqueImageView image_view;            // destroyed before image
    vk::UniqueFramebuffer
        framebuffer;              // destroyed before render_pass/image_view
    vk::UniquePipeline pipeline;  // destroyed before layout/renderpass
    vk::UniqueFence fence;        // destroyed FIRST
    int dma_fd = -1;
    uint32_t stride = 0;  // bytes per row; set by getImageSubresourceLayout

    ~VulkanState() noexcept {
      // Close the exported fd before the Vulkan memory object is released.
      if (dma_fd >= 0) {
        ::close(dma_fd);
        dma_fd = -1;
      }
      // vk::UniqueX members destroy automatically in reverse declaration order.
    }
    VulkanState() = default;
    VulkanState(const VulkanState&) = delete;
    VulkanState& operator=(const VulkanState&) = delete;
  } vk_;

  // linux_dmabuf_ — destroyed before vk_ so the compositor is told we are done
  // with the dmabuf global before the Vulkan memory is freed.
  wl::WlPtr<LinuxDmabufHandler> linux_dmabuf_;

  // wl_buffer_ — destroyed before linux_dmabuf_; sends wl_buffer.destroy to
  // the compositor so it can release its reference to the DMA-BUF.
  wl::WlPtr<WlBufferHandler> wl_buffer_;

  // XDG CRTP handlers — destroyed in reverse: toplevel first, wm_base last.
  wl::WlPtr<wl::XdgWmBaseHandler> xdg_wm_base_;
  wl::WlPtr<wl::XdgSurfaceHandler<App>> xdg_surface_;
  wl::WlPtr<wl::XdgToplevelHandler<App>> xdg_toplevel_;

  // Seat + keyboard manager — keyboard_ inside is destroyed before a seat_.
  wl::SeatManager<App> seat_;

  // Frame-pacing callback — destroyed first among all WlPtrs.
  wl::WlPtr<WlCallbackHandler> frame_callback_;

  // Application state.
  bool running_ = true;
  bool configured_ = false;
  bool vulkan_init_ = false;
  int width_ = 250;
  int height_ = 250;
  // Compositor-requested dimensions from the latest xdg_toplevel::configure.
  // Non-zero means a resize is pending; applied at the start of RenderFrame().
  int pending_width_ = 0;
  int pending_height_ = 0;
  bool needs_resize_ = false;
  // Current rotation angle (radians), advanced by kRotStep each frame.
  float angle_ = 0.0f;

  // Global ids recorded during the registry scan.
  uint32_t compositor_name_ = 0, compositor_ver_ = 0;
  uint32_t xdg_wm_base_name_ = 0, xdg_wm_base_ver_ = 0;
  uint32_t linux_dmabuf_name_ = 0, linux_dmabuf_ver_ = 0;

  /// Maximum time (ms) to wait for a compositor response during start-up.
  static constexpr int kRoundtripTimeoutMs = 5000;
  /// Maximum DMA-BUF bind version we support (v3: format and modifier events,
  /// create_immed).  Capped regardless of what the compositor advertises.
  static constexpr uint32_t kDmaBufVersion = 3;
  /// Maximum dimension accepted (guards against compositor sending huge sizes).
  static constexpr int kMaxDim = 16384;
  /// Rotation step per frame (radians).  One full revolution every 2 seconds
  /// at 60 Hz, matching Weston's simple-dmabuf-vulkan animation speed.
  static constexpr float kRotStep = 2.0f * static_cast<float>(M_PI) / 120.0f;

  // ── Internal pipeline steps ─────────────────────────────────────────────
  bool ConnectDisplay();
  bool ScanGlobals();
  bool BindGlobals();
  bool CreateSurfaces();
  bool InitVulkan();
  bool CreateDmaBufBuffer();
  /// Run the render loop.  Returns true on a clean exit (the user closed the
  /// window or pressed ESC), false if the compositor disconnected unexpectedly.
  bool MainLoop();

  /// Register a wl_surface.frame callback with the compositor.
  void RequestFrameCallback() noexcept;

  /// Recreate size-dependent Vulkan resources (image, view, framebuffer,
  /// DMA-BUF fd, wl_buffer) when the compositor requests a new window size.
  /// Waits for GPU idle first.  Returns false on error.
  bool DoResize() noexcept;

  /// Render one frame: re-record the Vulkan command buffer, submit,
  /// wait for the fence, then arm the callback, attach, damage, and commit.
  void RenderFrame() noexcept;
};

// ══════════════════════════════════════════════════════════════════════════════
// Handler method implementations (need full App definition)
// ══════════════════════════════════════════════════════════════════════════════

void WlCallbackHandler::OnDone(const uint32_t time_ms) {
  app_->OnFrameReady(time_ms);
}

// ══════════════════════════════════════════════════════════════════════════════
// App method implementations
// ══════════════════════════════════════════════════════════════════════════════

App::~App() {
  // Send versioned seat/keyboard release requests before member destructors
  // run.  SeatManager::Release() calls wl_keyboard.release (v≥3) then
  // wl_seat.release (v≥5) before the WlPtr destructors fire.
  seat_.Release();

  // Everything else is handled by member destructors in declaration-reverse
  // order:
  //   frame_callback_ → seat_ → xdg_toplevel_ → xdg_surface_ → xdg_wm_base_
  //   → wl_buffer_ (wl_buffer.destroy) → linux_dmabuf_ (destroy request)
  //   → vk_ (VulkanState dtor: close(dma_fd) + Vulkan teardown)
  //   → surface_ (wl_surface.destroy) → compositor_ (wl_proxy_destroy)
  //   → registry_ → display_ (disconnect).
}

int App::Run() {
  // Apply CLI dimensions before Vulkan allocates the image.
  width_ = opts_.width;
  height_ = opts_.height;

  if (!ConnectDisplay())
    return EXIT_FAILURE;
  if (!ScanGlobals())
    return EXIT_FAILURE;
  if (!BindGlobals())
    return EXIT_FAILURE;
  if (!CreateSurfaces())
    return EXIT_FAILURE;
  if (!InitVulkan())
    return EXIT_FAILURE;
  if (!CreateDmaBufBuffer())
    return EXIT_FAILURE;
  return MainLoop() ? EXIT_SUCCESS : EXIT_FAILURE;
}

// ── ConnectDisplay
// ────────────────────────────────────────────────────────────

bool App::ConnectDisplay() {
  if (!display_.Connect()) {
    std::fprintf(stderr, "xdg-simple-dmabuf-vulkan: wl_display_connect: %s\n",
                 std::strerror(errno));
    return false;
  }
  return true;
}

// ── ScanGlobals
// ───────────────────────────────────────────────────────────────

bool App::ScanGlobals() {
  if (!registry_.Create(display_.Get())) {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: wl_display_get_registry failed\n");
    return false;
  }

  registry_.OnGlobal([this](wl::CRegistry& /*reg*/, const uint32_t name,
                            const std::string_view iface, const uint32_t ver) {
    using wl_comp = wayland::client::wl_compositor_traits;
    using xdg_base = xdg_shell::client::xdg_wm_base_traits;
    using wl_s = wayland::client::wl_seat_traits;
    using dmabuf = linux_dmabuf_unstable_v1::client::zwp_linux_dmabuf_v1_traits;

    if (iface == wl_comp::interface_name) {
      compositor_name_ = name;
      compositor_ver_ = ver;
    } else if (iface == xdg_base::interface_name) {
      xdg_wm_base_name_ = name;
      xdg_wm_base_ver_ = ver;
    } else if (iface == wl_s::interface_name) {
      seat_.Record(name, ver);
    } else if (iface == dmabuf::interface_name) {
      linux_dmabuf_name_ = name;
      linux_dmabuf_ver_ = ver;
    }
  });

  if (!wl::RoundtripWithTimeout(display_.Get(), kRoundtripTimeoutMs)) {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: timed out waiting for global "
                 "advertisements\n");
    return false;
  }

  if (!compositor_name_) {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: wl_compositor not advertised\n");
    return false;
  }
  if (!xdg_wm_base_name_) {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: xdg_wm_base not advertised\n");
    return false;
  }
  if (!linux_dmabuf_name_) {
    std::fprintf(
        stderr,
        "xdg-simple-dmabuf-vulkan: zwp_linux_dmabuf_v1 not advertised\n");
    return false;
  }
  return true;
}

// ── BindGlobals
// ───────────────────────────────────────────────────────────────

bool App::BindGlobals() {
  using namespace wayland::client;
  using namespace xdg_shell::client;
  using namespace linux_dmabuf_unstable_v1::client;

  // wl_compositor — no events; use Attach() to skip listener installation.
  if (wl_proxy* raw = registry_.Bind<wl_compositor_traits>(
          compositor_name_,
          std::min(compositor_ver_, wl_compositor_traits::version))) {
    compositor_.Attach(raw);
  } else {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: wl_compositor bind failed\n");
    return false;
  }

  // xdg_wm_base — CRTP handler responds to ping automatically.
  if (!wl::BindHandler<xdg_wm_base_traits>(
          registry_, xdg_wm_base_, xdg_wm_base_name_, xdg_wm_base_ver_)) {
    std::fprintf(stderr, "xdg-simple-dmabuf-vulkan: xdg_wm_base bind failed\n");
    return false;
  }

  // zwp_linux_dmabuf_v1 — cap at kDmaBufVersion (v3) regardless of what the
  // compositor advertises; our wl_interface tables only cover v1–v3 messages.
  const uint32_t dmabuf_bind_ver = std::min(
      {linux_dmabuf_ver_, zwp_linux_dmabuf_v1_traits::version, kDmaBufVersion});
  if (!wl::BindHandler<zwp_linux_dmabuf_v1_traits>(
          registry_, linux_dmabuf_, linux_dmabuf_name_, dmabuf_bind_ver)) {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: zwp_linux_dmabuf_v1 bind failed\n");
    return false;
  }
  // Tell the handler which format to watch for.
  linux_dmabuf_.Get()->desired_format = opts_.drm_format;

  // Roundtrip so the compositor sends format/modifier events from the
  // linux-dmabuf global before we check format support.
  if (!wl::RoundtripWithTimeout(display_.Get(), kRoundtripTimeoutMs)) {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: timed out waiting for linux-dmabuf "
                 "formats\n");
    return false;
  }

  if (!linux_dmabuf_.Get()->has_format) {
    // Find the format name for a clear error message.
    const char* fmt_name = "unknown";
    for (const auto& e : kDrmFormats) {
      if (e.code == opts_.drm_format) {
        fmt_name = e.name;
        break;
      }
    }
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: compositor does not support "
                 "DRM_FORMAT_%s\n",
                 fmt_name);
    return false;
  }

  // wl_seat — optional; SeatManager::Bind() is a no-op if not advertised.
  if (!seat_.Bind(registry_, this)) {
    std::fprintf(stderr, "xdg-simple-dmabuf-vulkan: wl_seat bind failed\n");
    return false;
  }

  // Roundtrip so seat capabilities arrive before CreateSurfaces.
  if (!wl::RoundtripWithTimeout(display_.Get(), kRoundtripTimeoutMs)) {
    std::fprintf(
        stderr,
        "xdg-simple-dmabuf-vulkan: timed out waiting for seat capabilities\n");
    return false;
  }
  return true;
}

// ── CreateSurfaces
// ────────────────────────────────────────────────────────────

bool App::CreateSurfaces() {
  using namespace wayland::client;
  using namespace xdg_shell::client;

  // wl_compositor.create_surface → wl_surface.
  if (wl_proxy* raw = wl::construct<wl_surface_traits,
                                    wl_compositor_traits::Op::CreateSurface>(
          *compositor_.Get())) {
    surface_.Get()->_SetProxy(raw);
  } else {
    std::fprintf(
        stderr,
        "xdg-simple-dmabuf-vulkan: wl_compositor.create_surface failed\n");
    return false;
  }

  // xdg_wm_base.get_xdg_surface → xdg_surface.
  if (!wl::SetupHandler(xdg_surface_,
                        wl::construct<xdg_surface_traits,
                                      xdg_wm_base_traits::Op::GetXdgSurface>(
                            *xdg_wm_base_.Get(), surface_.Get()->GetProxy()))) {
    std::fprintf(
        stderr,
        "xdg-simple-dmabuf-vulkan: xdg_wm_base.get_xdg_surface failed\n");
    return false;
  }
  xdg_surface_.Get()->app_ = this;

  // xdg_surface.get_toplevel → xdg_toplevel.
  if (!wl::SetupHandler(xdg_toplevel_,
                        wl::construct<xdg_toplevel_traits,
                                      xdg_surface_traits::Op::GetToplevel>(
                            *xdg_surface_.Get()))) {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: xdg_surface.get_toplevel failed\n");
    return false;
  }
  xdg_toplevel_.Get()->app_ = this;

  xdg_toplevel_.Get()->SetTitle("xdg-simple-dmabuf-vulkan");
  xdg_toplevel_.Get()->SetAppId("org.wayland-cxx.xdg-simple-dmabuf-vulkan");

  // Empty commit to trigger the initial xdg_surface.configure roundtrip.
  // OnToplevelConfigure will record the compositor-suggested window size;
  // InitVulkan() will then allocate the image at that size.
  surface_.Get()->Commit();
  if (!wl::RoundtripWithTimeout(display_.Get(), kRoundtripTimeoutMs)) {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: timed out waiting for xdg_surface "
                 "configure\n");
    return false;
  }
  return true;
}

// ── InitVulkan
// ────────────────────────────────────────────────────────────────

bool App::InitVulkan() {
  // ── Instance ───────────────────────────────────────────────────────────────
  // Require Vulkan 1.1 so that VkExternalMemoryImageCreateInfo and
  // VkExportMemoryAllocateInfo are core (no KHR suffix needed).
  constexpr vk::ApplicationInfo app_info{"xdg-simple-dmabuf-vulkan",
                                         VK_MAKE_VERSION(0, 1, 0), nullptr, 0,
                                         VK_API_VERSION_1_1};
  const vk::InstanceCreateInfo inst_ci{{}, &app_info};
  auto inst_rv = vk::createInstanceUnique(inst_ci);
  if (!VkOk(inst_rv.result, "vkCreateInstance"))
    return false;
  vk_.instance = std::move(inst_rv.value);

  // ── Physical device ────────────────────────────────────────────────────────
  auto phys_rv = vk_.instance->enumeratePhysicalDevices();
  if (!VkOk(phys_rv.result, "vkEnumeratePhysicalDevices") ||
      phys_rv.value.empty()) {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: no Vulkan physical devices\n");
    return false;
  }
  vk_.phys_dev = phys_rv.value.at(0);

  // ── Graphics queue family ──────────────────────────────────────────────────
  const auto qfps = vk_.phys_dev.getQueueFamilyProperties();
  for (uint32_t i = 0; i < static_cast<uint32_t>(qfps.size()); ++i) {
    if (qfps.at(i).queueFlags & vk::QueueFlagBits::eGraphics) {
      vk_.queue_family = i;
      break;
    }
  }
  if (vk_.queue_family == UINT32_MAX) {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: no graphics queue family\n");
    return false;
  }

  // ── Device extension check ─────────────────────────────────────────────────
  auto ext_rv = vk_.phys_dev.enumerateDeviceExtensionProperties();
  if (!VkOk(ext_rv.result, "vkEnumerateDeviceExtensionProperties"))
    return false;
  constexpr std::string_view kExtFd = VK_KHR_EXTERNAL_MEMORY_FD_EXTENSION_NAME;
  const bool has_ext_fd =
      std::ranges::any_of(ext_rv.value, [&](const vk::ExtensionProperties& e) {
        return std::string_view{e.extensionName.data()} == kExtFd;
      });
  if (!has_ext_fd) {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: device missing extension %.*s\n",
                 static_cast<int>(kExtFd.size()), kExtFd.data());
    return false;
  }

  // ── Logical device ─────────────────────────────────────────────────────────
  constexpr float queue_prio = 1.0f;
  const vk::DeviceQueueCreateInfo queue_ci{
      {}, vk_.queue_family, 1, &queue_prio};
  // NOLINTBEGIN(cppcoreguidelines-avoid-c-arrays)
  static constexpr const char* kDevExts[] = {
      VK_KHR_EXTERNAL_MEMORY_FD_EXTENSION_NAME,
  };
  // NOLINTEND(cppcoreguidelines-avoid-c-arrays)
  const vk::DeviceCreateInfo dev_ci{{}, 1, &queue_ci, 0, nullptr, 1, kDevExts};
  auto dev_rv = vk_.phys_dev.createDeviceUnique(dev_ci);
  if (!VkOk(dev_rv.result, "vkCreateDevice"))
    return false;
  vk_.device = std::move(dev_rv.value);
  vk_.queue = vk_.device->getQueue(vk_.queue_family, 0);

  // ── Command pool ───────────────────────────────────────────────────────────
  const vk::CommandPoolCreateInfo pool_ci{
      vk::CommandPoolCreateFlagBits::eResetCommandBuffer, vk_.queue_family};
  auto pool_rv = vk_.device->createCommandPoolUnique(pool_ci);
  if (!VkOk(pool_rv.result, "vkCreateCommandPool"))
    return false;
  vk_.cmd_pool = std::move(pool_rv.value);

  // ── Exportable image ───────────────────────────────────────────────────────
  // VK_FORMAT_B8G8R8A8_UNORM maps to both DRM_FORMAT_XRGB8888 and
  // DRM_FORMAT_ARGB8888 (same memory layout on little-endian; distinction is
  // just whether the compositor honors the alpha channel).
  // VK_IMAGE_TILING_LINEAR is required for DMA-BUF export with the LINEAR
  // modifier (DRM_FORMAT_MOD_LINEAR = 0).
  constexpr vk::ExternalMemoryImageCreateInfo ext_img{
      vk::ExternalMemoryHandleTypeFlagBits::eDmaBufEXT};
  vk::ImageCreateInfo img_ci;
  img_ci.imageType = vk::ImageType::e2D;
  img_ci.format = vk::Format::eB8G8R8A8Unorm;
  img_ci.extent = vk::Extent3D{static_cast<uint32_t>(width_),
                               static_cast<uint32_t>(height_), 1};
  img_ci.mipLevels = 1;
  img_ci.arrayLayers = 1;
  img_ci.samples = vk::SampleCountFlagBits::e1;
  img_ci.tiling = vk::ImageTiling::eLinear;
  img_ci.usage = vk::ImageUsageFlagBits::eColorAttachment;
  img_ci.sharingMode = vk::SharingMode::eExclusive;
  img_ci.initialLayout = vk::ImageLayout::eUndefined;
  img_ci.setPNext(&ext_img);

  auto img_rv = vk_.device->createImageUnique(img_ci);
  if (!VkOk(img_rv.result, "vkCreateImage"))
    return false;
  vk_.image = std::move(img_rv.value);

  // ── Memory allocation ──────────────────────────────────────────────────────
  const vk::MemoryRequirements mem_reqs =
      vk_.device->getImageMemoryRequirements(*vk_.image);

  // Query the row stride — required for the DMA-BUF import by the compositor.
  const vk::SubresourceLayout sub_layout =
      vk_.device->getImageSubresourceLayout(
          *vk_.image, {vk::ImageAspectFlagBits::eColor, 0, 0});
  vk_.stride = static_cast<uint32_t>(sub_layout.rowPitch);

  // Find a memory type that is compatible with the image and prefers
  // device-local (fast GPU-side) memory.
  const vk::PhysicalDeviceMemoryProperties mem_props =
      vk_.phys_dev.getMemoryProperties();
  uint32_t mem_type = UINT32_MAX;
  for (uint32_t i = 0; i < mem_props.memoryTypeCount; ++i) {
    if (!(mem_reqs.memoryTypeBits & (1u << i)))
      continue;
    if (mem_props.memoryTypes.at(i).propertyFlags &
        vk::MemoryPropertyFlagBits::eDeviceLocal) {
      mem_type = i;
      break;
    }
    if (mem_type == UINT32_MAX)
      mem_type = i;  // accept any compatible type as fallback
  }
  if (mem_type == UINT32_MAX) {
    std::fprintf(stderr,
                 "xdg-simple-dmabuf-vulkan: no suitable Vulkan memory type\n");
    return false;
  }

  constexpr vk::ExportMemoryAllocateInfo export_mem{
      vk::ExternalMemoryHandleTypeFlagBits::eDmaBufEXT};
  vk::MemoryAllocateInfo mem_ai{mem_reqs.size, mem_type};
  mem_ai.setPNext(&export_mem);

  auto mem_rv = vk_.device->allocateMemoryUnique(mem_ai);
  if (!VkOk(mem_rv.result, "vkAllocateMemory"))
    return false;
  vk_.memory = std::move(mem_rv.value);

  if (!VkOk(vk_.device->bindImageMemory(*vk_.image, *vk_.memory, 0),
            "vkBindImageMemory"))
    return false;

  // ── Export DMA-BUF fd ──────────────────────────────────────────────────────
  // getMemoryFdKHR returns a fresh O_RDWR file descriptor.  We keep it for
  // the lifetime of the application; the compositor receives a dup via the
  // Wayland fd-passing mechanism when we call zwp_linux_buffer_params_v1::add.
  //
  // vkGetMemoryFdKHR is a VK_KHR_external_memory_fd device-level extension
  // entry point.  libvulkan.so only exports core loader symbols at link time,
  // so the function must be resolved at runtime via vkGetDeviceProcAddr.
  // We call the C API directly to avoid needing
  // VULKAN_HPP_DISPATCH_LOADER_DYNAMIC.
  {
    const auto fn = reinterpret_cast<PFN_vkGetMemoryFdKHR>(
        vkGetDeviceProcAddr(*vk_.device, "vkGetMemoryFdKHR"));
    if (!fn) {
      std::fprintf(
          stderr,
          "xdg-simple-dmabuf-vulkan: vkGetDeviceProcAddr(vkGetMemoryFdKHR) "
          "returned null\n");
      return false;
    }
    const VkMemoryGetFdInfoKHR fd_info_c{
        VK_STRUCTURE_TYPE_MEMORY_GET_FD_INFO_KHR, nullptr, *vk_.memory,
        VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT};
    int raw_fd = -1;
    if (!VkOk(static_cast<vk::Result>(fn(*vk_.device, &fd_info_c, &raw_fd)),
              "vkGetMemoryFdKHR"))
      return false;
    vk_.dma_fd = raw_fd;
  }

  // ── Vertex buffer ──────────────────────────────────────────────────────────
  // HOST_VISIBLE | HOST_COHERENT so we can map and copy the triangle data
  // from the CPU.
  {
    constexpr vk::BufferCreateInfo buf_ci{
        {},
        sizeof(kTriangle),
        vk::BufferUsageFlagBits::eVertexBuffer,
        vk::SharingMode::eExclusive};
    auto vb_rv = vk_.device->createBufferUnique(buf_ci);
    if (!VkOk(vb_rv.result, "vkCreateBuffer (vertex)"))
      return false;
    vk_.vertex_buf = std::move(vb_rv.value);

    const vk::MemoryRequirements vb_reqs =
        vk_.device->getBufferMemoryRequirements(*vk_.vertex_buf);
    constexpr vk::MemoryPropertyFlags want =
        vk::MemoryPropertyFlagBits::eHostVisible |
        vk::MemoryPropertyFlagBits::eHostCoherent;
    uint32_t vb_mem_type = UINT32_MAX;
    for (uint32_t i = 0; i < mem_props.memoryTypeCount; ++i) {
      if (!(vb_reqs.memoryTypeBits & (1u << i)))
        continue;
      if ((mem_props.memoryTypes.at(i).propertyFlags & want) == want) {
        vb_mem_type = i;
        break;
      }
    }
    if (vb_mem_type == UINT32_MAX) {
      std::fprintf(stderr,
                   "xdg-simple-dmabuf-vulkan: no host-visible memory for "
                   "vertex buffer\n");
      return false;
    }
    auto vm_rv = vk_.device->allocateMemoryUnique({vb_reqs.size, vb_mem_type});
    if (!VkOk(vm_rv.result, "vkAllocateMemory (vertex)"))
      return false;
    vk_.vertex_mem = std::move(vm_rv.value);
    if (!VkOk(vk_.device->bindBufferMemory(*vk_.vertex_buf, *vk_.vertex_mem, 0),
              "vkBindBufferMemory (vertex)"))
      return false;

    // Upload triangle data.
    auto map_rv = vk_.device->mapMemory(*vk_.vertex_mem, 0, vb_reqs.size);
    if (!VkOk(map_rv.result, "vkMapMemory (vertex)"))
      return false;
    std::memcpy(map_rv.value, kTriangle, sizeof(kTriangle));
    vk_.device->unmapMemory(*vk_.vertex_mem);
  }

  // ── Render pass ────────────────────────────────────────────────────────────
  // Single BGRA color attachment.
  //   Load = eClear → clear to black at the start of every render pass.
  //   Store = eStore → keep results so the compositor can read them.
  //   initialLayout = eUndefined → a driver may discard contents (we always
  //                                 clear, so this is safe and avoids a
  //                                 layout-transition cost on the first frame).
  //   finalLayout = eGeneral → suitable for DMA-BUF / CPU reads by the
  //                                 compositor.
  {
    constexpr vk::AttachmentDescription color_att{
        {},
        vk::Format::eB8G8R8A8Unorm,
        vk::SampleCountFlagBits::e1,
        vk::AttachmentLoadOp::eClear,
        vk::AttachmentStoreOp::eStore,
        vk::AttachmentLoadOp::eDontCare,
        vk::AttachmentStoreOp::eDontCare,
        vk::ImageLayout::eUndefined,
        vk::ImageLayout::eGeneral,
    };
    constexpr vk::AttachmentReference color_ref{
        0, vk::ImageLayout::eColorAttachmentOptimal};
    const vk::SubpassDescription subpass{
        {}, vk::PipelineBindPoint::eGraphics, 0, nullptr, 1, &color_ref};
    // Subpass dependency: ensure the render pass output is visible to external
    // (compositor DMA) readers before the next frame's render pass begins.
    constexpr vk::SubpassDependency dep{
        0,
        VK_SUBPASS_EXTERNAL,
        vk::PipelineStageFlagBits::eColorAttachmentOutput,
        vk::PipelineStageFlagBits::eBottomOfPipe,
        vk::AccessFlagBits::eColorAttachmentWrite,
        vk::AccessFlagBits::eMemoryRead,
        vk::DependencyFlagBits::eByRegion};
    const vk::RenderPassCreateInfo rp_ci{{},       1, &color_att, 1,
                                         &subpass, 1, &dep};
    auto rp_rv = vk_.device->createRenderPassUnique(rp_ci);
    if (!VkOk(rp_rv.result, "vkCreateRenderPass"))
      return false;
    vk_.render_pass = std::move(rp_rv.value);
  }

  // ── Image view ─────────────────────────────────────────────────────────────
  {
    const vk::ImageViewCreateInfo iv_ci{
        {},
        *vk_.image,
        vk::ImageViewType::e2D,
        vk::Format::eB8G8R8A8Unorm,
        {},
        {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1}};
    auto iv_rv = vk_.device->createImageViewUnique(iv_ci);
    if (!VkOk(iv_rv.result, "vkCreateImageView"))
      return false;
    vk_.image_view = std::move(iv_rv.value);
  }

  // ── Framebuffer ────────────────────────────────────────────────────────────
  {
    const vk::ImageView attachments[] = {*vk_.image_view};
    const vk::FramebufferCreateInfo fb_ci{{},
                                          *vk_.render_pass,
                                          1,
                                          attachments,
                                          static_cast<uint32_t>(width_),
                                          static_cast<uint32_t>(height_),
                                          1};
    auto fb_rv = vk_.device->createFramebufferUnique(fb_ci);
    if (!VkOk(fb_rv.result, "vkCreateFramebuffer"))
      return false;
    vk_.framebuffer = std::move(fb_rv.value);
  }

  // ── Shader modules ─────────────────────────────────────────────────────────
  {
    const vk::ShaderModuleCreateInfo vert_ci{{}, sizeof(kVertSpv), kVertSpv};
    auto vm_rv = vk_.device->createShaderModuleUnique(vert_ci);
    if (!VkOk(vm_rv.result, "vkCreateShaderModule (vert)"))
      return false;
    vk_.vert_module = std::move(vm_rv.value);
  }
  {
    constexpr vk::ShaderModuleCreateInfo frag_ci{
        {}, sizeof(kFragSpv), kFragSpv};
    auto fm_rv = vk_.device->createShaderModuleUnique(frag_ci);
    if (!VkOk(fm_rv.result, "vkCreateShaderModule (frag)"))
      return false;
    vk_.frag_module = std::move(fm_rv.value);
  }

  // ── Pipeline layout ────────────────────────────────────────────────────────
  // One push constant range: a single float (angle, in radians) at offset 0,
  // used by the vertex shader to rotate the triangle each frame.
  {
    constexpr vk::PushConstantRange pc_range{vk::ShaderStageFlagBits::eVertex,
                                             0, sizeof(float)};
    const vk::PipelineLayoutCreateInfo layout_ci{{}, 0, nullptr, 1, &pc_range};
    auto pl_rv = vk_.device->createPipelineLayoutUnique(layout_ci);
    if (!VkOk(pl_rv.result, "vkCreatePipelineLayout"))
      return false;
    vk_.pipeline_layout = std::move(pl_rv.value);
  }

  // ── Graphics pipeline ──────────────────────────────────────────────────────
  // Vertex binding 0: interleaved [x, y, r, g, b] per vertex.
  //   Attribute 0: vec2 position at offset 0.
  //   Attribute 1: vec3 color at offset offsetof(Vertex, r) = 8.
  // Viewport and scissor are dynamic state, so the pipeline does not need to
  // be recreated when the window is resized.
  {
    constexpr vk::VertexInputBindingDescription binding{
        0, sizeof(Vertex), vk::VertexInputRate::eVertex};
    constexpr vk::VertexInputAttributeDescription attrs[2]{
        {0, 0, vk::Format::eR32G32Sfloat,
         static_cast<uint32_t>(offsetof(Vertex, x))},
        {1, 0, vk::Format::eR32G32B32Sfloat,
         static_cast<uint32_t>(offsetof(Vertex, r))},
    };
    const vk::PipelineVertexInputStateCreateInfo vert_input{
        {}, 1, &binding, 2, attrs};

    constexpr vk::PipelineInputAssemblyStateCreateInfo input_asm{
        {}, vk::PrimitiveTopology::eTriangleList, VK_FALSE};

    // Counts must be declared even with dynamic state; actual values are set
    // per-draw via vkCmdSetViewport / vkCmdSetScissor in RenderFrame().
    constexpr vk::PipelineViewportStateCreateInfo viewport_state{
        {}, 1, nullptr, 1, nullptr};

    constexpr vk::PipelineRasterizationStateCreateInfo raster{
        {},
        VK_FALSE,
        VK_FALSE,
        vk::PolygonMode::eFill,
        vk::CullModeFlagBits::eNone,
        vk::FrontFace::eCounterClockwise,
        VK_FALSE,
        0.0f,
        0.0f,
        0.0f,
        1.0f};

    constexpr vk::PipelineMultisampleStateCreateInfo msaa{
        {}, vk::SampleCountFlagBits::e1};

    constexpr vk::ColorComponentFlags kAllComponents =
        vk::ColorComponentFlagBits::eR | vk::ColorComponentFlagBits::eG |
        vk::ColorComponentFlagBits::eB | vk::ColorComponentFlagBits::eA;
    constexpr vk::PipelineColorBlendAttachmentState blend_att{
        VK_FALSE, {}, {}, {}, {}, {}, {}, kAllComponents};
    const vk::PipelineColorBlendStateCreateInfo blend{
        {}, VK_FALSE, vk::LogicOp::eCopy, 1, &blend_att};

    constexpr vk::DynamicState dyn_states[2]{vk::DynamicState::eViewport,
                                             vk::DynamicState::eScissor};
    const vk::PipelineDynamicStateCreateInfo dyn_state{{}, 2, dyn_states};

    const vk::PipelineShaderStageCreateInfo stages[2]{
        {{}, vk::ShaderStageFlagBits::eVertex, *vk_.vert_module, "main"},
        {{}, vk::ShaderStageFlagBits::eFragment, *vk_.frag_module, "main"},
    };

    const vk::GraphicsPipelineCreateInfo pipe_ci{{},
                                                 2,
                                                 stages,
                                                 &vert_input,
                                                 &input_asm,
                                                 nullptr,
                                                 &viewport_state,
                                                 &raster,
                                                 &msaa,
                                                 nullptr,
                                                 &blend,
                                                 &dyn_state,
                                                 *vk_.pipeline_layout,
                                                 *vk_.render_pass,
                                                 0};
    auto pipe_rv = vk_.device->createGraphicsPipelineUnique({}, pipe_ci);
    if (!VkOk(pipe_rv.result, "vkCreateGraphicsPipelines"))
      return false;
    vk_.pipeline = std::move(pipe_rv.value);
  }

  // ── Command buffer ─────────────────────────────────────────────────────────
  const vk::CommandBufferAllocateInfo cb_ai{
      *vk_.cmd_pool, vk::CommandBufferLevel::ePrimary, 1};
  auto cb_rv = vk_.device->allocateCommandBuffersUnique(cb_ai);
  if (!VkOk(cb_rv.result, "vkAllocateCommandBuffers"))
    return false;
  vk_.cmd_buf = std::move(cb_rv.value.front());

  // ── Fence ──────────────────────────────────────────────────────────────────
  auto fence_rv = vk_.device->createFenceUnique({});
  if (!VkOk(fence_rv.result, "vkCreateFence"))
    return false;
  vk_.fence = std::move(fence_rv.value);

  vulkan_init_ = true;
  std::printf(
      "xdg-simple-dmabuf-vulkan: Vulkan initialized "
      "(stride=%u, dma_fd=%d)\n",
      vk_.stride, vk_.dma_fd);
  return true;
}

// ── CreateDmaBufBuffer
// ────────────────────────────────────────────────────────

bool App::CreateDmaBufBuffer() {
  using namespace linux_dmabuf_unstable_v1::client;
  using namespace wayland::client;

  // Create a transient zwp_linux_buffer_params_v1 to build the wl_buffer.
  // We use Attach() (not SetupHandler) because we take the create_immed
  // synchronous path and never need to receive created/failed events.
  wl::WlPtr<LinuxBufferParamsHandler> params;
  if (wl_proxy* raw =
          wl::construct<zwp_linux_buffer_params_v1_traits,
                        zwp_linux_dmabuf_v1_traits::Op::CreateParams>(
              *linux_dmabuf_.Get())) {
    params.Attach(raw);
  } else {
    std::fprintf(
        stderr,
        "xdg-simple-dmabuf-vulkan: zwp_linux_dmabuf_v1.create_params failed\n");
    return false;
  }

  // Add our DMA-BUF plane.  The fd is sent via SCM_RIGHTS (libwayland dups it
  // during marshalling); our copy vk_.dma_fd remains valid afterwards.
  // Modifier: DRM_FORMAT_MOD_LINEAR = 0.
  params.Get()->Add(vk_.dma_fd, 0u, 0u, vk_.stride,
                    static_cast<uint32_t>(
                        static_cast<uint64_t>(DRM_FORMAT_MOD_LINEAR) >> 32u),
                    static_cast<uint32_t>(DRM_FORMAT_MOD_LINEAR));

  // create_immed synchronously returns a wl_buffer proxy on the client side
  // without waiting for a compositor round-trip.
  if (wl_proxy* raw =
          wl::construct<wl_buffer_traits,
                        zwp_linux_buffer_params_v1_traits::Op::CreateImmed>(
              *params.Get(), static_cast<int32_t>(width_),
              static_cast<int32_t>(height_), opts_.drm_format, 0u)) {
    // Use _SetProxy to install the event listener for wl_buffer.release.
    wl_buffer_.Get()->_SetProxy(raw);
  } else {
    std::fprintf(
        stderr,
        "xdg-simple-dmabuf-vulkan: zwp_linux_buffer_params_v1.create_immed "
        "failed\n");
    return false;
  }

  // params goes out of scope here — WlPtr::~WlPtr() sends
  // zwp_linux_buffer_params_v1.destroy and calls wl_proxy_destroy.
  // Mark the new buffer as available (not held by the compositor yet).
  wl_buffer_.Get()->released_ = true;
  return true;
}

// ── DoResize
// ──────────────────────────────────────────────────────────────────

bool App::DoResize() noexcept {
  const int new_w = (pending_width_ > 0) ? pending_width_ : width_;
  const int new_h = (pending_height_ > 0) ? pending_height_ : height_;

  if (new_w == width_ && new_h == height_)
    return true;  // Nothing to do.

  std::printf("xdg-simple-dmabuf-vulkan: resize %dx%d → %dx%d\n", width_,
              height_, new_w, new_h);

  // Wait for any in-flight GPU work to finish before touching Vulkan objects.
  if (!VkOk(vk_.device->waitIdle(), "vkDeviceWaitIdle (resize)"))
    return false;

  // Destroy the old wl_buffer.  This sends wl_buffer.destroy to the
  // compositor, which is the correct way to relinquish our claim on the
  // DMA-BUF.
  wl_buffer_.Reset();

  // Destroy size-dependent Vulkan objects in reverse creation order.
  vk_.framebuffer.reset();
  vk_.image_view.reset();
  vk_.image.reset();

  // Close the old DMA-BUF fd before freeing the memory it is backed by.
  if (vk_.dma_fd >= 0) {
    ::close(vk_.dma_fd);
    vk_.dma_fd = -1;
  }
  vk_.memory.reset();

  // Apply the new size.
  width_ = new_w;
  height_ = new_h;

  // ── Recreate the exportable image ─────────────────────────────────────────
  constexpr vk::ExternalMemoryImageCreateInfo ext_img{
      vk::ExternalMemoryHandleTypeFlagBits::eDmaBufEXT};
  vk::ImageCreateInfo img_ci;
  img_ci.imageType = vk::ImageType::e2D;
  img_ci.format = vk::Format::eB8G8R8A8Unorm;
  img_ci.extent = vk::Extent3D{static_cast<uint32_t>(width_),
                               static_cast<uint32_t>(height_), 1};
  img_ci.mipLevels = 1;
  img_ci.arrayLayers = 1;
  img_ci.samples = vk::SampleCountFlagBits::e1;
  img_ci.tiling = vk::ImageTiling::eLinear;
  img_ci.usage = vk::ImageUsageFlagBits::eColorAttachment;
  img_ci.sharingMode = vk::SharingMode::eExclusive;
  img_ci.initialLayout = vk::ImageLayout::eUndefined;
  img_ci.setPNext(&ext_img);

  {
    auto img_rv = vk_.device->createImageUnique(img_ci);
    if (!VkOk(img_rv.result, "vkCreateImage (resize)"))
      return false;
    vk_.image = std::move(img_rv.value);
  }

  // ── Allocate and bind memory ───────────────────────────────────────────────
  const vk::MemoryRequirements mem_reqs =
      vk_.device->getImageMemoryRequirements(*vk_.image);
  const vk::SubresourceLayout sub_layout =
      vk_.device->getImageSubresourceLayout(
          *vk_.image, {vk::ImageAspectFlagBits::eColor, 0, 0});
  vk_.stride = static_cast<uint32_t>(sub_layout.rowPitch);

  const vk::PhysicalDeviceMemoryProperties mem_props =
      vk_.phys_dev.getMemoryProperties();
  uint32_t mem_type = UINT32_MAX;
  for (uint32_t i = 0; i < mem_props.memoryTypeCount; ++i) {
    if (!(mem_reqs.memoryTypeBits & (1u << i)))
      continue;
    if (mem_props.memoryTypes.at(i).propertyFlags &
        vk::MemoryPropertyFlagBits::eDeviceLocal) {
      mem_type = i;
      break;
    }
    if (mem_type == UINT32_MAX)
      mem_type = i;
  }
  if (mem_type == UINT32_MAX) {
    std::fprintf(
        stderr,
        "xdg-simple-dmabuf-vulkan: no suitable Vulkan memory type (resize)\n");
    return false;
  }

  constexpr vk::ExportMemoryAllocateInfo export_mem{
      vk::ExternalMemoryHandleTypeFlagBits::eDmaBufEXT};
  vk::MemoryAllocateInfo mem_ai{mem_reqs.size, mem_type};
  mem_ai.setPNext(&export_mem);

  {
    auto mem_rv = vk_.device->allocateMemoryUnique(mem_ai);
    if (!VkOk(mem_rv.result, "vkAllocateMemory (resize)"))
      return false;
    vk_.memory = std::move(mem_rv.value);
  }
  if (!VkOk(vk_.device->bindImageMemory(*vk_.image, *vk_.memory, 0),
            "vkBindImageMemory (resize)"))
    return false;

  // ── Export new DMA-BUF fd ──────────────────────────────────────────────────
  {
    const auto fn = reinterpret_cast<PFN_vkGetMemoryFdKHR>(
        vkGetDeviceProcAddr(*vk_.device, "vkGetMemoryFdKHR"));
    if (!fn) {
      std::fprintf(stderr,
                   "xdg-simple-dmabuf-vulkan: vkGetDeviceProcAddr("
                   "vkGetMemoryFdKHR) null (resize)\n");
      return false;
    }
    const VkMemoryGetFdInfoKHR fd_info_c{
        VK_STRUCTURE_TYPE_MEMORY_GET_FD_INFO_KHR, nullptr, *vk_.memory,
        VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT};
    int raw_fd = -1;
    if (!VkOk(static_cast<vk::Result>(fn(*vk_.device, &fd_info_c, &raw_fd)),
              "vkGetMemoryFdKHR (resize)"))
      return false;
    vk_.dma_fd = raw_fd;
  }

  // ── Recreate image view ────────────────────────────────────────────────────
  {
    const vk::ImageViewCreateInfo iv_ci{
        {},
        *vk_.image,
        vk::ImageViewType::e2D,
        vk::Format::eB8G8R8A8Unorm,
        {},
        {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1}};
    auto iv_rv = vk_.device->createImageViewUnique(iv_ci);
    if (!VkOk(iv_rv.result, "vkCreateImageView (resize)"))
      return false;
    vk_.image_view = std::move(iv_rv.value);
  }

  // ── Recreate framebuffer ───────────────────────────────────────────────────
  {
    const vk::ImageView attachments[] = {*vk_.image_view};
    const vk::FramebufferCreateInfo fb_ci{{},
                                          *vk_.render_pass,
                                          1,
                                          attachments,
                                          static_cast<uint32_t>(width_),
                                          static_cast<uint32_t>(height_),
                                          1};
    auto fb_rv = vk_.device->createFramebufferUnique(fb_ci);
    if (!VkOk(fb_rv.result, "vkCreateFramebuffer (resize)"))
      return false;
    vk_.framebuffer = std::move(fb_rv.value);
  }

  // ── Recreate wl_buffer ────────────────────────────────────────────────────
  return CreateDmaBufBuffer();
}

// ── MainLoop
// ──────────────────────────────────────────────────────────────────

bool App::MainLoop() {
  std::printf(
      "xdg-simple-dmabuf-vulkan: entering render loop (ESC or close to "
      "quit)\n");

  // Kickstart: render frame 0 (Vulkan GPU work), arm the first frame callback,
  // attach the DMA-BUF-backed wl_buffer, and commit.
  RenderFrame();

  const bool ok = wl::RunEventLoop(
      display_.Get(), [this] { return !running_; }, "xdg-simple-dmabuf-vulkan");
  if (ok)
    std::printf("xdg-simple-dmabuf-vulkan: exiting cleanly\n");
  return ok;
}

// ── RequestFrameCallback
// ──────────────────────────────────────────────────────

void App::RequestFrameCallback() noexcept {
  // wl_surface.frame → wl_callback.  Must be called BEFORE wl_surface.commit
  // so that the callback registration and the buffer attachment land in the
  // same compositor message batch.
  using wl_s = wayland::client::wl_surface_traits;
  using wl_c = wayland::client::wl_callback_traits;
  if (wl_proxy* raw = wl::construct<wl_c, wl_s::Op::Frame>(*surface_.Get())) {
    frame_callback_.Get()->app_ = this;
    frame_callback_.Get()->_SetProxy(raw);
  }
}

// ── RenderFrame
// ───────────────────────────────────────────────────────────────

void App::RenderFrame() noexcept {
  // Apply any pending resize before drawing.
  if (needs_resize_) {
    needs_resize_ = false;
    if (!DoResize()) {
      running_ = false;
      return;
    }
  }

  // ── Re-record the command buffer ──────────────────────────────────────────
  if (vk_.cmd_buf->reset({}) != vk::Result::eSuccess) {
    running_ = false;
    return;
  }
  if (vk_.cmd_buf->begin({vk::CommandBufferUsageFlagBits::eOneTimeSubmit}) !=
      vk::Result::eSuccess) {
    running_ = false;
    return;
  }

  // Clear to black, then draw the rotating red/green/blue triangle.
  // Push the current rotation angle to the vertex shader before drawing.
  constexpr vk::ClearValue clear_val{
      vk::ClearColorValue{std::array<float, 4>{0.0f, 0.0f, 0.0f, 1.0f}}};
  const vk::RenderPassBeginInfo rp_begin{
      *vk_.render_pass,
      *vk_.framebuffer,
      {{0, 0}, {static_cast<uint32_t>(width_), static_cast<uint32_t>(height_)}},
      1,
      &clear_val};
  vk_.cmd_buf->beginRenderPass(rp_begin, vk::SubpassContents::eInline);
  vk_.cmd_buf->bindPipeline(vk::PipelineBindPoint::eGraphics, *vk_.pipeline);

  // Set a dynamic viewport and scissor to cover the current surface dimensions.
  const vk::Viewport vp{
      0.0f, 0.0f, static_cast<float>(width_), static_cast<float>(height_),
      0.0f, 1.0f};
  vk_.cmd_buf->setViewport(0, 1, &vp);
  const vk::Rect2D scissor{
      {0, 0}, {static_cast<uint32_t>(width_), static_cast<uint32_t>(height_)}};
  vk_.cmd_buf->setScissor(0, 1, &scissor);

  // Upload the rotation angle as a push constant (offset 0, vertex stage).
  vk_.cmd_buf->pushConstants(*vk_.pipeline_layout,
                             vk::ShaderStageFlagBits::eVertex, 0, sizeof(float),
                             &angle_);
  // Advance the angle for the next frame.
  angle_ += kRotStep;
  if (angle_ >= 2.0f * static_cast<float>(M_PI))
    angle_ -= 2.0f * static_cast<float>(M_PI);

  constexpr vk::DeviceSize vert_off = 0;
  vk_.cmd_buf->bindVertexBuffers(0, 1, &*vk_.vertex_buf, &vert_off);
  vk_.cmd_buf->draw(3, 1, 0, 0);
  vk_.cmd_buf->endRenderPass();

  if (vk_.cmd_buf->end() != vk::Result::eSuccess) {
    running_ = false;
    return;
  }

  // ── Submit and wait for GPU completion ────────────────────────────────────
  // Waiting on the fence before attaching the buffer ensures the compositor
  // reads fully rendered pixels.  Implicit DMA-BUF fence support in the
  // kernel would remove the need for this CPU stall; we use the simple
  // synchronous path here to keep the example self-contained.
  const vk::SubmitInfo submit_info{{}, {}, *vk_.cmd_buf, {}};
  if (vk_.queue.submit(1, &submit_info, *vk_.fence) != vk::Result::eSuccess) {
    running_ = false;
    return;
  }
  if (vk_.device->waitForFences(*vk_.fence, VK_TRUE, UINT64_MAX) !=
      vk::Result::eSuccess) {
    running_ = false;
    return;
  }
  if (!VkOk(vk_.device->resetFences(*vk_.fence), "vkResetFences")) {
    running_ = false;
    return;
  }

  // ── Present via Wayland ───────────────────────────────────────────────────
  // Mark the buffer as "in use" so OnRelease() can track compositor ownership.
  wl_buffer_.Get()->released_ = false;
  // Register the frame callback BEFORE commit so the request lands in the
  // same message batch as the buffer attachment (required by the Wayland
  // protocol — the callback fires after the frame that contains it).
  RequestFrameCallback();
  surface_.Get()->Attach(wl_buffer_.Get()->GetProxy(), 0, 0);
  surface_.Get()->Damage(0, 0, width_, height_);
  surface_.Get()->Commit();
}

// ── OnFrameReady
// ──────────────────────────────────────────────────────────────

void App::OnFrameReady(uint32_t /*time_ms*/) noexcept {
  // Detach the now-spent wl_callback proxy before arming the next one.
  // Detach() sets m_proxy to nullptr so WlPtr::~WlPtr() will not double-free.
  wl_proxy* const spent_cb = frame_callback_.Detach();
  const auto guard = wl::ScopeExit{[spent_cb] {
    if (spent_cb)
      wl_proxy_destroy(spent_cb);
  }};

  // RenderFrame() re-arms the callback, submits GPU work, and commits.
  RenderFrame();
}

// ── App callbacks
// ─────────────────────────────────────────────────────────────

void App::OnXdgSurfaceConfigure(uint32_t /*serial*/) {
  // The framework already sent ack_configure before calling this callback.
  if (!configured_) {
    // First configure: if the compositor suggested a size, use it as the
    // initial window size (overriding the CLI default).
    if (pending_width_ > 0 && pending_height_ > 0) {
      width_ = pending_width_;
      height_ = pending_height_;
    }
    configured_ = true;
    return;
  }
  // schedule a resize if the compositor changed the size.
  if (!vulkan_init_)
    return;
  const int nw = (pending_width_ > 0) ? pending_width_ : width_;
  const int nh = (pending_height_ > 0) ? pending_height_ : height_;
  if (nw != width_ || nh != height_)
    needs_resize_ = true;
}

void App::OnToplevelConfigure(const int32_t w, const int32_t h) {
  // Always record the compositor-requested dimensions.
  // A zero value means "client may choose"; keep the current/CLI size in
  // that case.  Capped to kMaxDim to guard against bogus values.
  if (w > 0)
    pending_width_ = std::min(static_cast<int>(w), kMaxDim);
  if (h > 0)
    pending_height_ = std::min(static_cast<int>(h), kMaxDim);
}

void App::OnToplevelClose() {
  running_ = false;
}

void App::OnKey(const uint32_t key, const uint32_t state) {
  if (key == KEY_ESC && state == WL_KEYBOARD_KEY_STATE_PRESSED)
    running_ = false;
}

// ══════════════════════════════════════════════════════════════════════════════
// Entry point
// ══════════════════════════════════════════════════════════════════════════════

static void PrintUsage(const char* argv0) {
  std::printf(
      "Usage: %s [OPTIONS]\n"
      "\n"
      "Render a DMA-BUF-backed Vulkan triangle on a Wayland compositor.\n"
      "\n"
      "Options:\n"
      "  -f, --drm-format FORMAT  DRM pixel format name (default: XRGB8888)\n"
      "  -w, --width N            Window width  in pixels (default: 250)\n"
      "  -h, --height N           Window height in pixels (default: 250)\n"
      "      --help               Print this help and exit\n"
      "\n"
      "Supported DRM formats: XRGB8888, ARGB8888\n",
      argv0);
}

int main(int argc, char** argv) {
  // Suppress SIGPIPE so a compositor disconnect during wl_display_flush is
  // reported as EPIPE / error return rather than terminating the process.
  std::signal(SIGPIPE, SIG_IGN);

  App::Options opts{};

  // NOLINTBEGIN(cppcoreguidelines-avoid-c-arrays)
  static constexpr option kLongOpts[] = {
      {"drm-format", required_argument, nullptr, 'f'},
      {"width", required_argument, nullptr, 'w'},
      {"height", required_argument, nullptr, 'h'},
      {"help", no_argument, nullptr, '?'},
      {nullptr, 0, nullptr, 0},
  };
  // NOLINTEND(cppcoreguidelines-avoid-c-arrays)

  int opt;
  while ((opt = getopt_long(argc, argv, "f:w:h:", kLongOpts, nullptr)) != -1) {
    switch (opt) {
      case 'f': {
        const uint32_t code = ParseDrmFormat(optarg);
        if (!code) {
          std::fprintf(stderr,
                       "%s: unknown DRM format '%s'; "
                       "supported: XRGB8888, ARGB8888\n",
                       argv[0], optarg);
          return EXIT_FAILURE;
        }
        opts.drm_format = code;
        break;
      }
      case 'w':
        opts.width = static_cast<int>(std::strtol(optarg, nullptr, 10));
        if (opts.width <= 0) {
          std::fprintf(stderr, "%s: invalid width '%s'\n", argv[0], optarg);
          return EXIT_FAILURE;
        }
        break;
      case 'h':
        opts.height = static_cast<int>(std::strtol(optarg, nullptr, 10));
        if (opts.height <= 0) {
          std::fprintf(stderr, "%s: invalid height '%s'\n", argv[0], optarg);
          return EXIT_FAILURE;
        }
        break;
      case '?':
        PrintUsage(argv[0]);
        return EXIT_SUCCESS;
      default:
        PrintUsage(argv[0]);
        return EXIT_FAILURE;
    }
  }

  App app{opts};
  return app.Run();
}
