// dear imgui: Platform Backend for Wayland (via wayland-cxx-scanner)
// See imgui_impl_wayland_cxx.h for feature matrix and usage notes.
//
// SPDX-License-Identifier: MIT
//
// Architecture
// ------------
// The backend creates its own wl_registry on the application's wl_display
// (multiple registries per connection are legal) and binds wl_seat + wl_shm
// itself.  Input arrives through CRTP handlers generated by
// wayland-cxx-scanner:
//
//   BackendSeat     : CWlSeat<...>       capability tracking, creates the rest
//   BackendPointer  : CWlPointer<...>    written against the generated class
//                                        directly; see the note on it below for
//                                        why it is not wl::PointerHandler
//   wl::KeyboardHandler<Data>            xkbcommon keymap + timerfd key repeat,
//                                        reused as-is from the framework
//   wl::TouchHandler<Data>               single-touch mouse emulation hooks
//   wl::CursorManager                    theme loading + animated cursors
//
// All events funnel into ImGuiIO through the 1.87+ event API
// (AddKeyEvent / AddMousePosEvent / ...), matching upstream backends.

#include "imgui_impl_wayland_cxx.h"
#ifndef IMGUI_DISABLE

// ── Generated C++ protocol header ────────────────────────────────────────────
#include "wayland_client.hpp"

// ── System headers ───────────────────────────────────────────────────────────
extern "C" {
#include <linux/input-event-codes.h>
#include <time.h>
#include <wayland-client-protocol.h>  // WL_* enums + wl_*_interface symbols
#include <wayland-util.h>             // wl_fixed_to_double
}
#include <xkbcommon/xkbcommon.h>  // xkb_keysym_to_utf32

// ── Framework headers ────────────────────────────────────────────────────────
#include <wl/client_helpers.hpp>  // wl::BindHandler / wl::SetupHandler
#include <wl/cursor.hpp>          // wl::CursorManager
#include <wl/display.hpp>         // wl::RoundtripWithTimeout
#include <wl/keyboard.hpp>        // wl::KeyboardHandler, wl::KeyEvent
#include <wl/registry.hpp>        // wl::CRegistry
#include <wl/seat.hpp>            // inline wl_iface() for wl_seat/wl_keyboard
#include <wl/touch.hpp>           // wl::TouchHandler, wl::TouchPoint
#include <wl/wl_ptr.hpp>          // wl::WlPtr

#include <algorithm>
#include <cmath>
#include <cstdint>

// ══════════════════════════════════════════════════════════════════════════════
// wl_iface() definitions
//
// The generated traits declare wl_iface() out-of-line;
// <wayland-client-protocol.h> provides the extern wl_interface tables.
// <wl/seat.hpp> defines them inline for every interface SeatManager binds —
// wl_seat, wl_keyboard, wl_pointer and wl_touch — so the backend supplies only
// wl_shm, which it binds itself for the cursor.  Applications linking this
// backend must not define wl_shm again.
// ══════════════════════════════════════════════════════════════════════════════

namespace wayland::client {

const wl_interface& wl_shm_traits::wl_iface() noexcept {
  return wl_shm_interface;
}

}  // namespace wayland::client

// ══════════════════════════════════════════════════════════════════════════════
// Backend data
// ══════════════════════════════════════════════════════════════════════════════

struct ImGui_ImplWaylandCxx_Data;

// ── BackendSeat ──────────────────────────────────────────────────────────────
// Owns nothing itself; forwards capability changes to the backend data so
// keyboard / pointer / touch proxies are created and released on demand.
struct BackendSeat : public wayland::client::CWlSeat<BackendSeat> {
  ImGui_ImplWaylandCxx_Data* bd = nullptr;
  void OnCapabilities(uint32_t caps) override;
  void OnName(const char* /*name*/) override {}
};

// ── BackendPointer ───────────────────────────────────────────────────────────
// Derives from the generated CWlPointer directly rather than using the
// framework's wl::PointerHandler.
//
// The original reason — that the helper left scroll at its generated no-op
// defaults — is gone: wl::PointerHandler now normalizes the whole axis family
// behind OnPointerAxis / OnPointerFrame, which is a straight replacement for
// the accumulation below.
//
// What still blocks the swap is enter/leave: this backend must ignore any
// surface that is not the application's, and wl::PointerEvent does not carry
// the surface, so the filtering in OnEnter/OnLeave cannot be expressed through
// the helper's hooks.  Adopting it means adding the surface to that event
// first.
struct BackendPointer : public wayland::client::CWlPointer<BackendPointer> {
  ImGui_ImplWaylandCxx_Data* bd = nullptr;

  void OnEnter(uint32_t serial,
               wl_proxy* surface,
               wl_fixed_t sx,
               wl_fixed_t sy) override;
  void OnLeave(uint32_t serial, wl_proxy* surface) override;
  void OnMotion(uint32_t time, wl_fixed_t sx, wl_fixed_t sy) override;
  void OnButton(uint32_t serial,
                uint32_t time,
                uint32_t button,
                uint32_t state) override;
  void OnAxis(uint32_t time, uint32_t axis, wl_fixed_t value) override;
  void OnAxisDiscrete(uint32_t axis, int32_t discrete) override;
  void OnAxisValue120(uint32_t axis, int32_t value120) override;
  void OnFrame() override;
};

struct ImGui_ImplWaylandCxx_Data {
  wl_display* display = nullptr;
  wl_proxy* surface = nullptr;  // application's wl_surface (borrowed)

  // Protocol objects.  Declaration order = reverse destruction order; the
  // registry is destroyed last among Wayland objects (before the borrowed
  // display, which the application owns).
  wl::CRegistry registry;
  wl::WlPtr<BackendSeat> seat;
  struct ShmHandler : public wayland::client::CWlShm<ShmHandler> {};
  wl::WlPtr<ShmHandler> shm;
  wl::WlPtr<wl::KeyboardHandler<ImGui_ImplWaylandCxx_Data>> keyboard;
  wl::WlPtr<BackendPointer> pointer;
  wl::WlPtr<wl::TouchHandler<ImGui_ImplWaylandCxx_Data>> touch;
  wl::CursorManager cursor;

  // Registry scan results.
  uint32_t seat_name = 0, seat_ver_adv = 0, seat_ver = 0;
  uint32_t shm_name = 0, shm_ver_adv = 0;

  // Surface geometry (logical) + content scale, fed by the application.
  int width = 0;
  int height = 0;
  float scale = 1.0f;

  // Frame timing.
  uint64_t last_frame_ns = 0;

  // Pointer state.
  bool pointer_inside = false;
  uint32_t enter_serial = 0;
  ImGuiMouseCursor last_cursor = ImGuiMouseCursor_COUNT;  // force first apply

  // Scroll accumulation, flushed on wl_pointer.frame.  Hi-res value120
  // (v8+) wins over continuous axis within a frame; axis_discrete (v5-7)
  // is normalized into the same v120 accumulator.
  double axis_x = 0.0, axis_y = 0.0;  // continuous, surface units
  double v120_x = 0.0, v120_y = 0.0;  // 120 == one detent
  bool has_v120 = false;
  bool pointer_frame_supported = false;  // wl_pointer v5+

  // Touch mouse-emulation state.
  int32_t active_touch = -1;

  // Keyboard state.
  bool focus_lost = false;
  bool ctrl_l = false, ctrl_r = false;
  bool shift_l = false, shift_r = false;
  bool alt_l = false, alt_r = false;
  bool super_l = false, super_r = false;

  // ── Hooks required by wl::KeyboardHandler<Data> ───────────────────────────
  void OnKey(const wl::KeyEvent& ev);
  // Optional hook, detected by KeyboardHandler via SFINAE.
  void OnKeyboardLeave();

  // ── Hooks detected by wl::TouchHandler<Data> via SFINAE ──────────────────
  void OnTouchDown(const wl::TouchPoint& p);
  void OnTouchMotion(const wl::TouchPoint& p);
  void OnTouchUp(int32_t id);
  void OnTouchCancel();

  // ── Internal helpers ──────────────────────────────────────────────────────
  void OnSeatCapabilities(uint32_t caps);
  void FlushScroll();
  void UpdateModifier(uint32_t evdev_key, bool down, ImGuiIO& io);
  void ApplyMouseCursor(ImGuiMouseCursor c);

  void ReleaseInput() {
    using namespace wayland::client;
    if (!touch.IsNull()) {
      if (seat_ver >= wl_touch_traits::Op::Since::Release)
        touch.Get()->Release();
      touch.Reset();
    }
    if (!pointer.IsNull()) {
      if (seat_ver >= wl_pointer_traits::Op::Since::Release)
        pointer.Get()->Release();
      pointer.Reset();
    }
    if (!keyboard.IsNull()) {
      if (seat_ver >= wl_keyboard_traits::Op::Since::Release)
        keyboard.Get()->Release();
      keyboard.Reset();
    }
  }
};

// Follows the multi-context convention of upstream backends.
static ImGui_ImplWaylandCxx_Data* ImGui_ImplWaylandCxx_GetBackendData() {
  return ImGui::GetCurrentContext()
             ? static_cast<ImGui_ImplWaylandCxx_Data*>(
                   ImGui::GetIO().BackendPlatformUserData)
             : nullptr;
}

static uint64_t NowNs() {
  timespec ts{};
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return static_cast<uint64_t>(ts.tv_sec) * 1000000000ull +
         static_cast<uint64_t>(ts.tv_nsec);
}

// ══════════════════════════════════════════════════════════════════════════════
// Key mapping: Linux evdev keycode → ImGuiKey
// ══════════════════════════════════════════════════════════════════════════════

static ImGuiKey ImGui_ImplWaylandCxx_KeyToImGuiKey(uint32_t key) {
  // clang-format off
  switch (key) {
    case KEY_TAB:        return ImGuiKey_Tab;
    case KEY_LEFT:       return ImGuiKey_LeftArrow;
    case KEY_RIGHT:      return ImGuiKey_RightArrow;
    case KEY_UP:         return ImGuiKey_UpArrow;
    case KEY_DOWN:       return ImGuiKey_DownArrow;
    case KEY_PAGEUP:     return ImGuiKey_PageUp;
    case KEY_PAGEDOWN:   return ImGuiKey_PageDown;
    case KEY_HOME:       return ImGuiKey_Home;
    case KEY_END:        return ImGuiKey_End;
    case KEY_INSERT:     return ImGuiKey_Insert;
    case KEY_DELETE:     return ImGuiKey_Delete;
    case KEY_BACKSPACE:  return ImGuiKey_Backspace;
    case KEY_SPACE:      return ImGuiKey_Space;
    case KEY_ENTER:      return ImGuiKey_Enter;
    case KEY_ESC:        return ImGuiKey_Escape;
    case KEY_APOSTROPHE: return ImGuiKey_Apostrophe;
    case KEY_COMMA:      return ImGuiKey_Comma;
    case KEY_MINUS:      return ImGuiKey_Minus;
    case KEY_DOT:        return ImGuiKey_Period;
    case KEY_SLASH:      return ImGuiKey_Slash;
    case KEY_SEMICOLON:  return ImGuiKey_Semicolon;
    case KEY_EQUAL:      return ImGuiKey_Equal;
    case KEY_LEFTBRACE:  return ImGuiKey_LeftBracket;
    case KEY_BACKSLASH:  return ImGuiKey_Backslash;
    case KEY_RIGHTBRACE: return ImGuiKey_RightBracket;
    case KEY_GRAVE:      return ImGuiKey_GraveAccent;
    case KEY_CAPSLOCK:   return ImGuiKey_CapsLock;
    case KEY_SCROLLLOCK: return ImGuiKey_ScrollLock;
    case KEY_NUMLOCK:    return ImGuiKey_NumLock;
    case KEY_SYSRQ:      return ImGuiKey_PrintScreen;
    case KEY_PAUSE:      return ImGuiKey_Pause;
    case KEY_KP0:        return ImGuiKey_Keypad0;
    case KEY_KP1:        return ImGuiKey_Keypad1;
    case KEY_KP2:        return ImGuiKey_Keypad2;
    case KEY_KP3:        return ImGuiKey_Keypad3;
    case KEY_KP4:        return ImGuiKey_Keypad4;
    case KEY_KP5:        return ImGuiKey_Keypad5;
    case KEY_KP6:        return ImGuiKey_Keypad6;
    case KEY_KP7:        return ImGuiKey_Keypad7;
    case KEY_KP8:        return ImGuiKey_Keypad8;
    case KEY_KP9:        return ImGuiKey_Keypad9;
    case KEY_KPDOT:      return ImGuiKey_KeypadDecimal;
    case KEY_KPSLASH:    return ImGuiKey_KeypadDivide;
    case KEY_KPASTERISK: return ImGuiKey_KeypadMultiply;
    case KEY_KPMINUS:    return ImGuiKey_KeypadSubtract;
    case KEY_KPPLUS:     return ImGuiKey_KeypadAdd;
    case KEY_KPENTER:    return ImGuiKey_KeypadEnter;
    case KEY_KPEQUAL:    return ImGuiKey_KeypadEqual;
    case KEY_LEFTCTRL:   return ImGuiKey_LeftCtrl;
    case KEY_LEFTSHIFT:  return ImGuiKey_LeftShift;
    case KEY_LEFTALT:    return ImGuiKey_LeftAlt;
    case KEY_LEFTMETA:   return ImGuiKey_LeftSuper;
    case KEY_RIGHTCTRL:  return ImGuiKey_RightCtrl;
    case KEY_RIGHTSHIFT: return ImGuiKey_RightShift;
    case KEY_RIGHTALT:   return ImGuiKey_RightAlt;
    case KEY_RIGHTMETA:  return ImGuiKey_RightSuper;
    case KEY_COMPOSE:    return ImGuiKey_Menu;
    case KEY_0:          return ImGuiKey_0;
    case KEY_1:          return ImGuiKey_1;
    case KEY_2:          return ImGuiKey_2;
    case KEY_3:          return ImGuiKey_3;
    case KEY_4:          return ImGuiKey_4;
    case KEY_5:          return ImGuiKey_5;
    case KEY_6:          return ImGuiKey_6;
    case KEY_7:          return ImGuiKey_7;
    case KEY_8:          return ImGuiKey_8;
    case KEY_9:          return ImGuiKey_9;
    case KEY_A:          return ImGuiKey_A;
    case KEY_B:          return ImGuiKey_B;
    case KEY_C:          return ImGuiKey_C;
    case KEY_D:          return ImGuiKey_D;
    case KEY_E:          return ImGuiKey_E;
    case KEY_F:          return ImGuiKey_F;
    case KEY_G:          return ImGuiKey_G;
    case KEY_H:          return ImGuiKey_H;
    case KEY_I:          return ImGuiKey_I;
    case KEY_J:          return ImGuiKey_J;
    case KEY_K:          return ImGuiKey_K;
    case KEY_L:          return ImGuiKey_L;
    case KEY_M:          return ImGuiKey_M;
    case KEY_N:          return ImGuiKey_N;
    case KEY_O:          return ImGuiKey_O;
    case KEY_P:          return ImGuiKey_P;
    case KEY_Q:          return ImGuiKey_Q;
    case KEY_R:          return ImGuiKey_R;
    case KEY_S:          return ImGuiKey_S;
    case KEY_T:          return ImGuiKey_T;
    case KEY_U:          return ImGuiKey_U;
    case KEY_V:          return ImGuiKey_V;
    case KEY_W:          return ImGuiKey_W;
    case KEY_X:          return ImGuiKey_X;
    case KEY_Y:          return ImGuiKey_Y;
    case KEY_Z:          return ImGuiKey_Z;
    case KEY_F1:         return ImGuiKey_F1;
    case KEY_F2:         return ImGuiKey_F2;
    case KEY_F3:         return ImGuiKey_F3;
    case KEY_F4:         return ImGuiKey_F4;
    case KEY_F5:         return ImGuiKey_F5;
    case KEY_F6:         return ImGuiKey_F6;
    case KEY_F7:         return ImGuiKey_F7;
    case KEY_F8:         return ImGuiKey_F8;
    case KEY_F9:         return ImGuiKey_F9;
    case KEY_F10:        return ImGuiKey_F10;
    case KEY_F11:        return ImGuiKey_F11;
    case KEY_F12:        return ImGuiKey_F12;
    case KEY_F13:        return ImGuiKey_F13;
    case KEY_F14:        return ImGuiKey_F14;
    case KEY_F15:        return ImGuiKey_F15;
    case KEY_F16:        return ImGuiKey_F16;
    case KEY_F17:        return ImGuiKey_F17;
    case KEY_F18:        return ImGuiKey_F18;
    case KEY_F19:        return ImGuiKey_F19;
    case KEY_F20:        return ImGuiKey_F20;
    case KEY_F21:        return ImGuiKey_F21;
    case KEY_F22:        return ImGuiKey_F22;
    case KEY_F23:        return ImGuiKey_F23;
    case KEY_F24:        return ImGuiKey_F24;
    default:             return ImGuiKey_None;
  }
  // clang-format on
}

// ══════════════════════════════════════════════════════════════════════════════
// Seat capabilities
// ══════════════════════════════════════════════════════════════════════════════

void BackendSeat::OnCapabilities(uint32_t caps) {
  if (bd != nullptr)
    bd->OnSeatCapabilities(caps);
}

void ImGui_ImplWaylandCxx_Data::OnSeatCapabilities(uint32_t caps) {
  using namespace wayland::client;

  const bool has_kbd = (caps & WL_SEAT_CAPABILITY_KEYBOARD) != 0u;
  if (has_kbd && keyboard.IsNull()) {
    if (wl::SetupHandler(
            keyboard,
            wl::construct<wl_keyboard_traits, wl_seat_traits::Op::GetKeyboard>(
                *seat.Get()))) {
      keyboard.Get()->app_ = this;
    }
  } else if (!has_kbd && !keyboard.IsNull()) {
    if (seat_ver >= wl_keyboard_traits::Op::Since::Release)
      keyboard.Get()->Release();
    keyboard.Reset();
  }

  const bool has_ptr = (caps & WL_SEAT_CAPABILITY_POINTER) != 0u;
  if (has_ptr && pointer.IsNull()) {
    if (wl::SetupHandler(
            pointer,
            wl::construct<wl_pointer_traits, wl_seat_traits::Op::GetPointer>(
                *seat.Get()))) {
      pointer.Get()->bd = this;
      pointer_frame_supported =
          seat_ver >= wl_pointer_traits::Evt::Since::Frame;
    }
  } else if (!has_ptr && !pointer.IsNull()) {
    if (seat_ver >= wl_pointer_traits::Op::Since::Release)
      pointer.Get()->Release();
    pointer.Reset();
    pointer_inside = false;
  }

  const bool has_touch = (caps & WL_SEAT_CAPABILITY_TOUCH) != 0u;
  if (has_touch && touch.IsNull()) {
    if (wl::SetupHandler(
            touch, wl::construct<wl_touch_traits, wl_seat_traits::Op::GetTouch>(
                       *seat.Get()))) {
      touch.Get()->app_ = this;
    }
  } else if (!has_touch && !touch.IsNull()) {
    if (seat_ver >= wl_touch_traits::Op::Since::Release)
      touch.Get()->Release();
    touch.Reset();
    active_touch = -1;
  }
}

// ══════════════════════════════════════════════════════════════════════════════
// Pointer events
// ══════════════════════════════════════════════════════════════════════════════

void BackendPointer::OnEnter(uint32_t serial,
                             wl_proxy* surface,
                             wl_fixed_t sx,
                             wl_fixed_t sy) {
  // Filter to the application surface; the cursor surface (or any other
  // surface the app creates) must not feed ImGui.
  if (surface != bd->surface) {
    bd->pointer_inside = false;
    return;
  }
  bd->pointer_inside = true;
  bd->enter_serial = serial;

  ImGuiIO& io = ImGui::GetIO();
  io.AddMouseSourceEvent(ImGuiMouseSource_Mouse);
  io.AddMousePosEvent(static_cast<float>(wl_fixed_to_double(sx)),
                      static_cast<float>(wl_fixed_to_double(sy)));

  // The compositor resets the cursor image on every enter; force a re-apply
  // of whatever shape ImGui currently wants.
  bd->cursor.Reset();
  bd->last_cursor = ImGuiMouseCursor_COUNT;
}

void BackendPointer::OnLeave(uint32_t /*serial*/, wl_proxy* surface) {
  if (surface != bd->surface)
    return;
  bd->pointer_inside = false;
  bd->cursor.Reset();
  ImGui::GetIO().AddMousePosEvent(-FLT_MAX, -FLT_MAX);
}

void BackendPointer::OnMotion(uint32_t /*time*/, wl_fixed_t sx, wl_fixed_t sy) {
  if (!bd->pointer_inside)
    return;
  ImGuiIO& io = ImGui::GetIO();
  io.AddMouseSourceEvent(ImGuiMouseSource_Mouse);
  io.AddMousePosEvent(static_cast<float>(wl_fixed_to_double(sx)),
                      static_cast<float>(wl_fixed_to_double(sy)));
}

void BackendPointer::OnButton(uint32_t /*serial*/,
                              uint32_t /*time*/,
                              uint32_t button,
                              uint32_t state) {
  if (!bd->pointer_inside)
    return;
  int mouse_button = -1;
  switch (button) {
    case BTN_LEFT:
      mouse_button = 0;
      break;
    case BTN_RIGHT:
      mouse_button = 1;
      break;
    case BTN_MIDDLE:
      mouse_button = 2;
      break;
    case BTN_SIDE:
      mouse_button = 3;
      break;
    case BTN_EXTRA:
      mouse_button = 4;
      break;
    default:
      return;
  }
  ImGuiIO& io = ImGui::GetIO();
  io.AddMouseSourceEvent(ImGuiMouseSource_Mouse);
  io.AddMouseButtonEvent(mouse_button,
                         state == WL_POINTER_BUTTON_STATE_PRESSED);
}

void BackendPointer::OnAxis(uint32_t /*time*/,
                            uint32_t axis,
                            wl_fixed_t value) {
  if (!bd->pointer_inside)
    return;
  const double v = wl_fixed_to_double(value);
  if (axis == WL_POINTER_AXIS_VERTICAL_SCROLL)
    bd->axis_y += v;
  else if (axis == WL_POINTER_AXIS_HORIZONTAL_SCROLL)
    bd->axis_x += v;
  // wl_pointer < v5 never sends frame; deliver each axis event standalone.
  if (!bd->pointer_frame_supported)
    bd->FlushScroll();
}

void BackendPointer::OnAxisDiscrete(uint32_t axis, int32_t discrete) {
  // v5-7 detent count; normalize into the value120 accumulator.
  OnAxisValue120(axis, discrete * 120);
}

void BackendPointer::OnAxisValue120(uint32_t axis, int32_t value120) {
  if (!bd->pointer_inside)
    return;
  bd->has_v120 = true;
  if (axis == WL_POINTER_AXIS_VERTICAL_SCROLL)
    bd->v120_y += value120;
  else if (axis == WL_POINTER_AXIS_HORIZONTAL_SCROLL)
    bd->v120_x += value120;
}

void BackendPointer::OnFrame() {
  bd->FlushScroll();
}

void ImGui_ImplWaylandCxx_Data::FlushScroll() {
  float wheel_x = 0.0f;
  float wheel_y = 0.0f;
  if (has_v120) {
    // Hi-res / discrete detents: 120 == one wheel step.
    wheel_x = static_cast<float>(-v120_x / 120.0);
    wheel_y = static_cast<float>(-v120_y / 120.0);
  } else {
    // Continuous axis (touchpad two-finger scroll): libinput emits ~15
    // surface units per wheel-click equivalent, matching the convention
    // used by GLFW's and SDL's Wayland backends.
    wheel_x = static_cast<float>(-axis_x / 15.0);
    wheel_y = static_cast<float>(-axis_y / 15.0);
  }
  axis_x = axis_y = v120_x = v120_y = 0.0;
  has_v120 = false;
  if (wheel_x != 0.0f || wheel_y != 0.0f) {
    ImGuiIO& io = ImGui::GetIO();
    io.AddMouseSourceEvent(ImGuiMouseSource_Mouse);
    io.AddMouseWheelEvent(wheel_x, wheel_y);
  }
}

// ══════════════════════════════════════════════════════════════════════════════
// Keyboard events (delivered by wl::KeyboardHandler<Data>)
// ══════════════════════════════════════════════════════════════════════════════

void ImGui_ImplWaylandCxx_Data::UpdateModifier(uint32_t evdev_key,
                                               bool down,
                                               ImGuiIO& io) {
  switch (evdev_key) {
    case KEY_LEFTCTRL:
      ctrl_l = down;
      break;
    case KEY_RIGHTCTRL:
      ctrl_r = down;
      break;
    case KEY_LEFTSHIFT:
      shift_l = down;
      break;
    case KEY_RIGHTSHIFT:
      shift_r = down;
      break;
    case KEY_LEFTALT:
      alt_l = down;
      break;
    case KEY_RIGHTALT:
      alt_r = down;
      break;
    case KEY_LEFTMETA:
      super_l = down;
      break;
    case KEY_RIGHTMETA:
      super_r = down;
      break;
    default:
      return;
  }
  io.AddKeyEvent(ImGuiMod_Ctrl, ctrl_l || ctrl_r);
  io.AddKeyEvent(ImGuiMod_Shift, shift_l || shift_r);
  io.AddKeyEvent(ImGuiMod_Alt, alt_l || alt_r);
  io.AddKeyEvent(ImGuiMod_Super, super_l || super_r);
}

void ImGui_ImplWaylandCxx_Data::OnKey(const wl::KeyEvent& ev) {
  ImGuiIO& io = ImGui::GetIO();
  const bool down = ev.state == WL_KEYBOARD_KEY_STATE_PRESSED;

  // Regain focus lazily: wl_keyboard has no enter hook exposed, but a key
  // event implies our surface holds keyboard focus.
  if (focus_lost) {
    focus_lost = false;
    io.AddFocusEvent(true);
  }

  if (!ev.repeat) {
    // Modifiers must reach ImGui before the key they modify.
    UpdateModifier(ev.key, down, io);

    const ImGuiKey key = ImGui_ImplWaylandCxx_KeyToImGuiKey(ev.key);
    if (key != ImGuiKey_None) {
      io.AddKeyEvent(key, down);
      io.SetKeyEventNativeData(key, static_cast<int>(ev.keysym),
                               static_cast<int>(ev.key));
    }
  }
  // Repeat events (compositor rate) feed text input only; key-level repeat
  // is handled by ImGui itself (io.KeyRepeatDelay / io.KeyRepeatRate),
  // matching the GLFW / SDL backends.

  if (down && ev.keysym != XKB_KEY_NoSymbol &&
      !(ctrl_l || ctrl_r)) {  // Ctrl chords are commands, not text
    const uint32_t cp = xkb_keysym_to_utf32(ev.keysym);
    if (cp >= 0x20 && cp != 0x7F)
      io.AddInputCharacter(cp);
  }
}

void ImGui_ImplWaylandCxx_Data::OnKeyboardLeave() {
  focus_lost = true;
  ctrl_l = ctrl_r = shift_l = shift_r = false;
  alt_l = alt_r = super_l = super_r = false;
  // Clears all held keys and modifiers inside ImGui.
  ImGui::GetIO().AddFocusEvent(false);
}

// ══════════════════════════════════════════════════════════════════════════════
// Touch events (single-touch mouse emulation)
// ══════════════════════════════════════════════════════════════════════════════

void ImGui_ImplWaylandCxx_Data::OnTouchDown(const wl::TouchPoint& p) {
  if (active_touch != -1)
    return;  // ignore additional fingers
  active_touch = p.id;
  ImGuiIO& io = ImGui::GetIO();
  io.AddMouseSourceEvent(ImGuiMouseSource_TouchScreen);
  io.AddMousePosEvent(static_cast<float>(p.x), static_cast<float>(p.y));
  io.AddMouseButtonEvent(0, true);
}

void ImGui_ImplWaylandCxx_Data::OnTouchMotion(const wl::TouchPoint& p) {
  if (p.id != active_touch)
    return;
  ImGuiIO& io = ImGui::GetIO();
  io.AddMouseSourceEvent(ImGuiMouseSource_TouchScreen);
  io.AddMousePosEvent(static_cast<float>(p.x), static_cast<float>(p.y));
}

void ImGui_ImplWaylandCxx_Data::OnTouchUp(int32_t id) {
  if (id != active_touch)
    return;
  active_touch = -1;
  ImGuiIO& io = ImGui::GetIO();
  io.AddMouseSourceEvent(ImGuiMouseSource_TouchScreen);
  io.AddMouseButtonEvent(0, false);
  // Touch has no hover; remove the cursor so widgets don't stay highlighted.
  io.AddMousePosEvent(-FLT_MAX, -FLT_MAX);
}

void ImGui_ImplWaylandCxx_Data::OnTouchCancel() {
  if (active_touch == -1)
    return;
  active_touch = -1;
  ImGuiIO& io = ImGui::GetIO();
  io.AddMouseSourceEvent(ImGuiMouseSource_TouchScreen);
  io.AddMouseButtonEvent(0, false);
  io.AddMousePosEvent(-FLT_MAX, -FLT_MAX);
}

// ══════════════════════════════════════════════════════════════════════════════
// Mouse cursor shapes
// ══════════════════════════════════════════════════════════════════════════════

static const char* ImGui_ImplWaylandCxx_CursorName(ImGuiMouseCursor c) {
  // XDG cursor-spec names; wl::CursorManager falls back through the legacy
  // X11 aliases ("left_ptr", "xterm", ...) via the theme itself.
  switch (c) {
    case ImGuiMouseCursor_Arrow:
      return "default";
    case ImGuiMouseCursor_TextInput:
      return "text";
    case ImGuiMouseCursor_ResizeAll:
      return "all-scroll";
    case ImGuiMouseCursor_ResizeNS:
      return "ns-resize";
    case ImGuiMouseCursor_ResizeEW:
      return "ew-resize";
    case ImGuiMouseCursor_ResizeNESW:
      return "nesw-resize";
    case ImGuiMouseCursor_ResizeNWSE:
      return "nwse-resize";
    case ImGuiMouseCursor_Hand:
      return "pointer";
    case ImGuiMouseCursor_Wait:
      return "wait";
    case ImGuiMouseCursor_Progress:
      return "progress";
    case ImGuiMouseCursor_NotAllowed:
      return "not-allowed";
    default:
      return "default";
  }
}

void ImGui_ImplWaylandCxx_Data::ApplyMouseCursor(ImGuiMouseCursor c) {
  if (pointer.IsNull() || !pointer_inside)
    return;
  wl_proxy* ptr_proxy = pointer.Get()->GetProxy();
  ImGuiIO& io = ImGui::GetIO();
  if (c == ImGuiMouseCursor_None || io.MouseDrawCursor) {
    cursor.Hide(ptr_proxy, enter_serial);
  } else {
    cursor.Set(ptr_proxy, enter_serial, ImGui_ImplWaylandCxx_CursorName(c));
  }
}

// ══════════════════════════════════════════════════════════════════════════════
// Public API
// ══════════════════════════════════════════════════════════════════════════════

bool ImGui_ImplWaylandCxx_Init(wl_display* display,
                               wl_surface* surface,
                               wl_compositor* compositor) {
  ImGuiIO& io = ImGui::GetIO();
  IMGUI_CHECKVERSION();
  IM_ASSERT(io.BackendPlatformUserData == nullptr &&
            "Already initialized a platform backend!");
  IM_ASSERT(display != nullptr && surface != nullptr);

  ImGui_ImplWaylandCxx_Data* bd = IM_NEW(ImGui_ImplWaylandCxx_Data)();
  io.BackendPlatformUserData = static_cast<void*>(bd);
  io.BackendPlatformName = "imgui_impl_wayland_cxx";
  io.BackendFlags |= ImGuiBackendFlags_HasMouseCursors;
  // Wayland cannot warp the pointer: no ImGuiBackendFlags_HasSetMousePos.

  bd->display = display;
  // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
  bd->surface = reinterpret_cast<wl_proxy*>(surface);
  bd->last_frame_ns = NowNs();

  // ── Registry scan (backend-private registry on the shared connection) ────
  if (!bd->registry.Create(display)) {
    ImGui_ImplWaylandCxx_Shutdown();
    return false;
  }
  bd->registry.OnGlobal([bd](wl::CRegistry&, uint32_t name,
                             std::string_view iface, uint32_t ver) {
    using namespace wayland::client;
    if (iface == wl_seat_traits::interface_name) {
      bd->seat_name = name;
      bd->seat_ver_adv = ver;
    } else if (iface == wl_shm_traits::interface_name) {
      bd->shm_name = name;
      bd->shm_ver_adv = ver;
    }
  });
  if (!wl::RoundtripWithTimeout(display)) {
    ImGui_ImplWaylandCxx_Shutdown();
    return false;
  }

  // ── Bind globals ──────────────────────────────────────────────────────────
  using namespace wayland::client;
  if (bd->seat_name != 0) {
    bd->seat_ver = std::min(bd->seat_ver_adv, wl_seat_traits::version);
    if (!wl::BindHandler<wl_seat_traits>(bd->registry, bd->seat, bd->seat_name,
                                         bd->seat_ver_adv)) {
      ImGui_ImplWaylandCxx_Shutdown();
      return false;
    }
    bd->seat.Get()->bd = bd;
  }
  if (bd->shm_name != 0) {
    // Cursor support is best-effort; a headless/kiosk compositor without a
    // pointer works fine without it.
    (void)wl::BindHandler<wl_shm_traits>(bd->registry, bd->shm, bd->shm_name,
                                         bd->shm_ver_adv);
  }

  // Seat capabilities arrive on this roundtrip → keyboard/pointer/touch are
  // created inside OnSeatCapabilities before Init returns.
  if (!wl::RoundtripWithTimeout(display)) {
    ImGui_ImplWaylandCxx_Shutdown();
    return false;
  }

  // ── Cursor theme (best-effort; needs wl_shm + the app's wl_compositor) ───
  // CursorManager creates its own cursor wl_surface through the libwayland C
  // API.  A failed Init leaves every cursor call a safe no-op, so a kiosk
  // compositor with no pointer or no theme installed still works.
  if (!bd->shm.IsNull() && compositor != nullptr) {
    // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
    (void)bd->cursor.Init(bd->shm.Get()->GetProxy(),
                          reinterpret_cast<wl_proxy*>(compositor),
                          static_cast<int>(std::ceil(bd->scale)));
  }

  return true;
}

void ImGui_ImplWaylandCxx_Shutdown() {
  ImGui_ImplWaylandCxx_Data* bd = ImGui_ImplWaylandCxx_GetBackendData();
  IM_ASSERT(bd != nullptr &&
            "No platform backend to shutdown, or already shutdown?");
  ImGuiIO& io = ImGui::GetIO();

  bd->cursor.Release();
  bd->ReleaseInput();
  if (!bd->seat.IsNull()) {
    using namespace wayland::client;
    if (bd->seat_ver >= wl_seat_traits::Op::Since::Release)
      bd->seat.Get()->Release();
    bd->seat.Reset();
  }
  bd->shm.Reset();
  bd->registry.Reset();

  io.BackendPlatformName = nullptr;
  io.BackendPlatformUserData = nullptr;
  io.BackendFlags &= ~ImGuiBackendFlags_HasMouseCursors;
  IM_DELETE(bd);
}

void ImGui_ImplWaylandCxx_NewFrame() {
  ImGui_ImplWaylandCxx_Data* bd = ImGui_ImplWaylandCxx_GetBackendData();
  IM_ASSERT(bd != nullptr &&
            "Context or backend not initialized! Did you call "
            "ImGui_ImplWaylandCxx_Init()?");
  ImGuiIO& io = ImGui::GetIO();

  // Display geometry: ImGui works in logical coordinates (matching the
  // surface-local pointer coordinates); the renderer scales by
  // DisplayFramebufferScale.
  io.DisplaySize =
      ImVec2(static_cast<float>(bd->width), static_cast<float>(bd->height));
  io.DisplayFramebufferScale = ImVec2(bd->scale, bd->scale);

  const uint64_t now = NowNs();
  uint64_t delta = now - bd->last_frame_ns;
  if (delta == 0)
    delta = 1;  // io.DeltaTime must be > 0
  io.DeltaTime = static_cast<float>(delta) * 1e-9f;
  bd->last_frame_ns = now;

  // Mouse cursor shape.
  const ImGuiMouseCursor c =
      io.MouseDrawCursor ? ImGuiMouseCursor_None : ImGui::GetMouseCursor();
  if (c != bd->last_cursor) {
    bd->last_cursor = c;
    bd->ApplyMouseCursor(c);
  }
}

void ImGui_ImplWaylandCxx_SetDisplaySize(int logical_w, int logical_h) {
  if (ImGui_ImplWaylandCxx_Data* bd = ImGui_ImplWaylandCxx_GetBackendData()) {
    bd->width = logical_w > 0 ? logical_w : 0;
    bd->height = logical_h > 0 ? logical_h : 0;
  }
}

void ImGui_ImplWaylandCxx_SetContentScale(float scale) {
  if (ImGui_ImplWaylandCxx_Data* bd = ImGui_ImplWaylandCxx_GetBackendData()) {
    if (scale <= 0.0f)
      scale = 1.0f;
    bd->scale = scale;
    // Cursor themes come in integer sizes; round up for crispness.
    bd->cursor.SetScale(static_cast<int>(std::ceil(scale)));
  }
}

int ImGui_ImplWaylandCxx_GetKeyRepeatFd() {
  ImGui_ImplWaylandCxx_Data* bd = ImGui_ImplWaylandCxx_GetBackendData();
  if (bd == nullptr || bd->keyboard.IsNull())
    return -1;
  return bd->keyboard.Get()->GetRepeatFd();
}

void ImGui_ImplWaylandCxx_DispatchKeyRepeat() {
  ImGui_ImplWaylandCxx_Data* bd = ImGui_ImplWaylandCxx_GetBackendData();
  if (bd != nullptr && !bd->keyboard.IsNull())
    bd->keyboard.Get()->DispatchRepeat();
}

int ImGui_ImplWaylandCxx_GetCursorFrameFd() {
  ImGui_ImplWaylandCxx_Data* bd = ImGui_ImplWaylandCxx_GetBackendData();
  return bd != nullptr ? bd->cursor.FrameFd() : -1;
}

void ImGui_ImplWaylandCxx_DispatchCursorFrame() {
  ImGui_ImplWaylandCxx_Data* bd = ImGui_ImplWaylandCxx_GetBackendData();
  if (bd != nullptr)
    bd->cursor.DispatchFrame();
}

#endif  // #ifndef IMGUI_DISABLE
