// SPDX-License-Identifier: MIT
// Copyright (c) 2026 wayland-cxx-scanner contributors
#include "codegen_c.hpp"

#include "name_transform.hpp"

#include <algorithm>
#include <cctype>
#include <sstream>

namespace wl::scanner {

using namespace ir;

namespace {

std::string to_upper(std::string_view s) {
    std::string out(s);
    std::transform(out.begin(), out.end(), out.begin(),
                   [](unsigned char c) { return static_cast<char>(std::toupper(c)); });
    return out;
}

void emit_enum(std::ostringstream& os, const Interface& iface, const Enum& en) {
    // e.g.  WL_FOO_ERROR_ROLE = 0,
    std::string prefix = to_upper(iface.name) + "_" + to_upper(en.name) + "_";
    os << "enum " << iface.name << "_" << en.name << " {\n";
    for (auto& e : en.entries) {
        os << "\t" << prefix << to_upper(e.name) << " = " << e.value << ",\n";
    }
    os << "};\n\n";
}

void emit_opcodes(std::ostringstream& os, const Interface& iface) {
    std::string prefix = to_upper(iface.name) + "_";
    for (auto& r : iface.requests) {
        os << "#define " << prefix << to_upper(r.name) << " " << r.opcode << "\n";
    }
    if (!iface.requests.empty())
        os << "\n";
    for (auto& e : iface.events) {
        os << "#define " << prefix << to_upper(e.name) << "_EVENT " << e.opcode << "\n";
    }
    if (!iface.events.empty())
        os << "\n";
}

void emit_since_versions(std::ostringstream& os, const Interface& iface) {
    std::string prefix = to_upper(iface.name) + "_";
    os << "#define " << prefix << "INTERFACE_VERSION " << iface.version << "\n\n";
}

}  // anonymous namespace

std::string generate_c_header(const Protocol& proto) {
    std::ostringstream os;

    os << "/* SPDX-License-Identifier: MIT */\n";
    os << "/* AUTO-GENERATED by wayland-cxx-scanner 0.1.0 — DO NOT EDIT */\n";
    os << "#pragma once\n\n";
    os << "#include <stdint.h>\n\n";
    os << "#ifdef __cplusplus\n";
    os << "extern \"C\" {\n";
    os << "#endif\n\n";
    os << "struct wl_interface;\n\n";

    for (auto& iface : proto.interfaces) {
        os << "/* interface " << iface.name << " */\n";
        os << "extern const struct wl_interface " << iface.name << "_interface;\n\n";
        emit_since_versions(os, iface);
        emit_opcodes(os, iface);
        for (auto& en : iface.enums)
            emit_enum(os, iface, en);
    }

    os << "#ifdef __cplusplus\n";
    os << "}\n";
    os << "#endif\n";
    return os.str();
}

}  // namespace wl::scanner
