// SPDX-License-Identifier: MIT
// Copyright (c) 2026 wayland-cxx-scanner contributors
//
// simple-egl — color-cycling EGL/OpenGL ES 2 Wayland client.
//
// Connects to the running compositor, creates an XDG toplevel window, and
// renders a hue-shifting solid colour via OpenGL ES 2 + EGL.
//
// Build requirements: wayland-client, wayland-egl, EGL, GLESv2.
// Runtime requirement: a running Wayland compositor with xdg-shell support.

// ── EGL/GLES headers (must precede any Wayland headers to avoid wl_display
//    redefinition issues on some EGL implementations) ─────────────────────────
extern "C" {
#include <EGL/egl.h>
#include <GLES2/gl2.h>
}

// ── Generated C++ protocol headers ───────────────────────────────────────────
// wayland_client.hpp → namespace wayland::client (from wayland.xml)
// xdg_shell_client.hpp → namespace xdg_shell::client (from xdg-shell.xml)
#include "wayland_client.hpp"
#include "xdg_shell_client.hpp"

// ── System Wayland C headers
// ──────────────────────────────────────────────────
extern "C" {
// Provides wl_*_interface symbols used by wl_iface() definitions below.
#include <wayland-client-protocol.h>
// Provides wl_egl_window_{create,destroy,resize}.
#include <wayland-egl.h>
// KEY_ESC and WL_KEYBOARD_KEY_STATE_PRESSED.
#include <linux/input-event-codes.h>
#include <unistd.h>  // close()
}

// ── Framework headers
// ─────────────────────────────────────────────────────────
#include <wl/registry.hpp>
#include <wl/wl_ptr.hpp>

// ── Standard library
// ──────────────────────────────────────────────────────────
#include <algorithm>
#include <cerrno>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iterator>  // std::data

// ── POSIX
// ─────────────────────────────────────────────────────────────────────
#include <poll.h>

// ══════════════════════════════════════════════════════════════════════════════
// wl_iface() definitions — core Wayland interfaces
//
// <wayland-client-protocol.h> exposes pre-built extern const wl_interface
// symbols for every core Wayland interface.  We simply forward to them.
// ══════════════════════════════════════════════════════════════════════════════

namespace wayland::client {

const wl_interface& wl_callback_traits::wl_iface() noexcept {
  return wl_callback_interface;
}
const wl_interface& wl_compositor_traits::wl_iface() noexcept {
  return wl_compositor_interface;
}
const wl_interface& wl_surface_traits::wl_iface() noexcept {
  return wl_surface_interface;
}
const wl_interface& wl_seat_traits::wl_iface() noexcept {
  return wl_seat_interface;
}
const wl_interface& wl_keyboard_traits::wl_iface() noexcept {
  return wl_keyboard_interface;
}

}  // namespace wayland::client

// ══════════════════════════════════════════════════════════════════════════════
// xdg-shell wl_interface definitions
//
// There is no pre-built system symbol for the xdg-shell interfaces (unlike
// core Wayland).  We reproduce the exact same tables that the C
// wayland-scanner generates from xdg-shell.xml (version 7) so that
// libwayland can type-check and dispatch correctly.
// ══════════════════════════════════════════════════════════════════════════════

// Forward declarations — the types array references all five interfaces before
// any of them are fully defined.  Using extern (external linkage) rather than
// static allows the declarations and definitions to match without duplication.
extern const wl_interface xdg_wm_base_iface_def;
extern const wl_interface xdg_positioner_iface_def;
extern const wl_interface xdg_surface_iface_def;
extern const wl_interface xdg_toplevel_iface_def;
extern const wl_interface xdg_popup_iface_def;

// Shared pointer array — layout mirrors xdg_shell_types[] from
// xdg-shell-protocol.c generated by the C wayland-scanner (version 7).
// Each message descriptor's `types` field points into this array at the
// offset corresponding to its first argument slot.
//
// NOLINTBEGIN(cppcoreguidelines-avoid-c-arrays,
//             cppcoreguidelines-avoid-non-const-global-variables,
//             cppcoreguidelines-interfaces-global-init)
// • avoid-non-const-global-variables: the element-pointer type must remain
//   non-const (const wl_interface*, not const wl_interface* const) because
//   wl_message::types is const wl_interface**; adding const to the elements
//   would change &xdg_shell_types[N] to const wl_interface* const*, which is
//   not implicitly convertible to const wl_interface** without a const_cast.
// • interfaces-global-init: the initializers only store object *addresses*,
//   which are link-time constants regardless of definition order (C++
//   [expr.const]: address of a static-storage-duration object is a constant
//   expression).  The apparent forward-reference to xdg_positioner_iface_def
//   etc. is therefore safe; this diagnostic is a false positive here.
static const wl_interface* xdg_shell_types[] = {
    nullptr,                    // [0]  scalar / no-type slots
    nullptr,                    // [1]
    nullptr,                    // [2]
    nullptr,                    // [3]
    &xdg_positioner_iface_def,  // [4]  create_positioner → new_id
    &xdg_surface_iface_def,     // [5]  get_xdg_surface   → new_id
    &wl_surface_interface,      // [6]  get_xdg_surface   → surface object
    &xdg_toplevel_iface_def,    // [7]  get_toplevel      → new_id
    &xdg_popup_iface_def,       // [8]  get_popup         → new_id
    &xdg_surface_iface_def,     // [9]  get_popup         → parent (?o)
    &xdg_positioner_iface_def,  // [10] get_popup         → positioner
    &xdg_toplevel_iface_def,    // [11] set_parent        → ?o
    &wl_seat_interface,         // [12] show_window_menu  → seat
    nullptr,                    // [13] show_window_menu  → serial
    nullptr,                    // [14] show_window_menu  → x
    nullptr,                    // [15] show_window_menu  → y
    &wl_seat_interface,         // [16] move              → seat
    nullptr,                    // [17] move              → serial
    &wl_seat_interface,         // [18] resize            → seat
    nullptr,                    // [19] resize            → serial
    nullptr,                    // [20] resize            → edges
    &wl_output_interface,       // [21] set_fullscreen    → output (?o)
    &wl_seat_interface,         // [22] grab              → seat
    nullptr,                    // [23] grab              → serial
    &xdg_positioner_iface_def,  // [24] reposition        → positioner
    nullptr,                    // [25] reposition        → token
};

// kScalarTypes: points at the null-filled head of xdg_shell_types[].
// Type is const wl_interface** — matching wl_message::types — without adding
// const to the pointer elements (which would break the implicit conversion).
// constexpr because &xdg_shell_types[0] is a constant expression (address of
// a static-storage-duration array element) and the constexpr wl_message
// arrays that use it must be initialised with constant expressions.
// NOLINTNEXTLINE(cppcoreguidelines-avoid-non-const-global-variables)
static constexpr const wl_interface** kScalarTypes = &xdg_shell_types[0];

// ── xdg_wm_base ──────────────────────────────────────────────────────────────
static constexpr wl_message xdg_wm_base_requests[] = {
    {"destroy", "", nullptr},  // no args
    {"create_positioner", "n", &xdg_shell_types[4]},
    {"get_xdg_surface", "no", &xdg_shell_types[5]},
    {"pong", "u", kScalarTypes},
};
static constexpr wl_message xdg_wm_base_events[] = {
    {"ping", "u", kScalarTypes},
};

// ── xdg_positioner ───────────────────────────────────────────────────────────
static constexpr wl_message xdg_positioner_requests[] = {
    {"destroy", "", nullptr},  // no args
    {"set_size", "ii", kScalarTypes},
    {"set_anchor_rect", "iiii", kScalarTypes},
    {"set_anchor", "u", kScalarTypes},
    {"set_gravity", "u", kScalarTypes},
    {"set_constraint_adjustment", "u", kScalarTypes},
    {"set_offset", "ii", kScalarTypes},
    {"set_reactive", "3", nullptr},  // no args (version tag only)
    {"set_parent_size", "3ii", kScalarTypes},
    {"set_parent_configure", "3u", kScalarTypes},
};

// ── xdg_surface ──────────────────────────────────────────────────────────────
static constexpr wl_message xdg_surface_requests[] = {
    {"destroy", "", nullptr},  // no args
    {"get_toplevel", "n", &xdg_shell_types[7]},
    {"get_popup", "n?oo", &xdg_shell_types[8]},
    {"set_window_geometry", "iiii", kScalarTypes},
    {"ack_configure", "u", kScalarTypes},
};
static constexpr wl_message xdg_surface_events[] = {
    {"configure", "u", kScalarTypes},
};

// ── xdg_toplevel ─────────────────────────────────────────────────────────────
static constexpr wl_message xdg_toplevel_requests[] = {
    {"destroy", "", nullptr},  // no args
    {"set_parent", "?o", &xdg_shell_types[11]},
    {"set_title", "s", kScalarTypes},
    {"set_app_id", "s", kScalarTypes},
    {"show_window_menu", "ouii", &xdg_shell_types[12]},
    {"move", "ou", &xdg_shell_types[16]},
    {"resize", "ouu", &xdg_shell_types[18]},
    {"set_max_size", "ii", kScalarTypes},
    {"set_min_size", "ii", kScalarTypes},
    {"set_maximized", "", nullptr},    // no args
    {"unset_maximized", "", nullptr},  // no args
    {"set_fullscreen", "?o", &xdg_shell_types[21]},
    {"unset_fullscreen", "", nullptr},  // no args
    {"set_minimized", "", nullptr},     // no args
};
static constexpr wl_message xdg_toplevel_events[] = {
    {"configure", "iia", kScalarTypes},
    {"close", "", nullptr},  // no args
    {"configure_bounds", "4ii", kScalarTypes},
    {"wm_capabilities", "5a", kScalarTypes},
};

// ── xdg_popup ────────────────────────────────────────────────────────────────
static constexpr wl_message xdg_popup_requests[] = {
    {"destroy", "", nullptr},  // no args
    {"grab", "ou", &xdg_shell_types[22]},
    {"reposition", "3ou", &xdg_shell_types[24]},
};
static constexpr wl_message xdg_popup_events[] = {
    {"configure", "iiii", kScalarTypes},
    {"popup_done", "", nullptr},  // no args
    {"repositioned", "3u", kScalarTypes},
};
// NOLINTEND(cppcoreguidelines-avoid-c-arrays,
//           cppcoreguidelines-avoid-non-const-global-variables,
//           cppcoreguidelines-interfaces-global-init)

// ── Interface object definitions
// ────────────────────────────────────────────── std::data() is used instead of
// a bare array name to make the array-to-pointer conversion explicit and
// suppress the array-decay diagnostic.
// clang-format off
const wl_interface xdg_wm_base_iface_def = {
    "xdg_wm_base",    7,
    4,  std::data(xdg_wm_base_requests),    1, std::data(xdg_wm_base_events)};
const wl_interface xdg_positioner_iface_def = {
    "xdg_positioner", 7,
    10, std::data(xdg_positioner_requests), 0, nullptr};
const wl_interface xdg_surface_iface_def = {
    "xdg_surface",    7,
    5,  std::data(xdg_surface_requests),    1, std::data(xdg_surface_events)};
const wl_interface xdg_toplevel_iface_def = {
    "xdg_toplevel",   7,
    14, std::data(xdg_toplevel_requests),   4, std::data(xdg_toplevel_events)};
const wl_interface xdg_popup_iface_def = {
    "xdg_popup",      7,
    3,  std::data(xdg_popup_requests),      3, std::data(xdg_popup_events)};
// clang-format on

namespace xdg_shell::client {

const wl_interface& xdg_wm_base_traits::wl_iface() noexcept {
  return xdg_wm_base_iface_def;
}
const wl_interface& xdg_positioner_traits::wl_iface() noexcept {
  return xdg_positioner_iface_def;
}
const wl_interface& xdg_surface_traits::wl_iface() noexcept {
  return xdg_surface_iface_def;
}
const wl_interface& xdg_toplevel_traits::wl_iface() noexcept {
  return xdg_toplevel_iface_def;
}
const wl_interface& xdg_popup_traits::wl_iface() noexcept {
  return xdg_popup_iface_def;
}

}  // namespace xdg_shell::client

// ══════════════════════════════════════════════════════════════════════════════
// CRTP handler classes
//
// Each handler inherits the generated CRTP base and overrides only the virtual
// event methods it cares about.  Constructor requests (get_xdg_surface,
// get_toplevel, get_keyboard, wl_surface.frame, …) are issued at the call site
// using wl::construct<ChildTraits, Opcode>(parent, args…) from proxy_impl.hpp
// — the WTL-pattern type-safe helper that encodes child interface and opcode as
// compile-time template arguments instead of runtime pointer/opcode pairs.
// ══════════════════════════════════════════════════════════════════════════════

// Forward-declare App so handler callbacks can call back into it.
class App;

// ── XdgWmBaseHandler ─────────────────────────────────────────────────────────

class XdgWmBaseHandler
    : public xdg_shell::client::CXdgWmBase<XdgWmBaseHandler> {
 public:
  App* app_ = nullptr;

  // Respond to compositor ping immediately.
  void OnPing(const uint32_t serial) override { Pong(serial); }
};

// ── XdgSurfaceHandler ────────────────────────────────────────────────────────

class XdgSurfaceHandler
    : public xdg_shell::client::CXdgSurface<XdgSurfaceHandler> {
 public:
  App* app_ = nullptr;

  void OnConfigure(uint32_t serial) override;
};

// ── XdgToplevelHandler ───────────────────────────────────────────────────────

class XdgToplevelHandler
    : public xdg_shell::client::CXdgToplevel<XdgToplevelHandler> {
 public:
  App* app_ = nullptr;

  void OnConfigure(int32_t w, int32_t h, wl_array* states) override;
  void OnClose() override;
  void OnConfigureBounds(int32_t /*w*/, int32_t /*h*/) override {}
  void OnWmCapabilities(wl_array* /*caps*/) override {}
};

// ── WlSeatHandler ────────────────────────────────────────────────────────────

class WlSeatHandler : public wayland::client::CWlSeat<WlSeatHandler> {
 public:
  App* app_ = nullptr;

  void OnCapabilities(uint32_t caps) override;
  void OnName(const char* /*name*/) override {}
};

// ── WlKeyboardHandler ────────────────────────────────────────────────────────

class WlKeyboardHandler
    : public wayland::client::CWlKeyboard<WlKeyboardHandler> {
 public:
  App* app_ = nullptr;

  // Close the keymap fd to avoid a leak (libwayland passes ownership).
  void OnKeymap(uint32_t /*fmt*/,
                const int32_t fd,
                uint32_t /*size*/) override {
    close(fd);
  }
  void OnEnter(uint32_t /*serial*/,
               wl_proxy* /*surface*/,
               wl_array* /*keys*/) override {}
  void OnLeave(uint32_t /*serial*/, wl_proxy* /*surface*/) override {}
  void OnKey(uint32_t /*serial*/,
             uint32_t /*time*/,
             uint32_t key,
             uint32_t state) override;
  void OnModifiers(uint32_t /*serial*/,
                   uint32_t /*mods_depressed*/,
                   uint32_t /*mods_latched*/,
                   uint32_t /*mods_locked*/,
                   uint32_t /*group*/) override {}
  void OnRepeatInfo(int32_t /*rate*/, int32_t /*delay*/) override {}
};

// ── WlCallbackHandler ────────────────────────────────────────────────────────
// Handles the one-shot wl_callback.done event emitted by the compositor to
// pace frame production.  A new instance (proxy) is allocated for every frame
// via wl_surface.frame; after done fires, the proxy is destroyed.

class WlCallbackHandler
    : public wayland::client::CWlCallback<WlCallbackHandler> {
 public:
  App* app_ = nullptr;

  void OnDone(uint32_t time_ms) override;
};

// ── WlCompositorHandler ──────────────────────────────────────────────────────
// wl_compositor has no events.  Provide the required ProcessEvent stub so the
// class is concrete.  We attach via WlPtr::Attach() rather than _SetProxy() so
// no listener table is needed (and none is generated for fewer interfaces).

class WlCompositorHandler
    : public wayland::client::CWlCompositor<WlCompositorHandler> {
 public:
  bool ProcessEvent(uint32_t, void**) override { return false; }
};

// ── WlSurfaceHandler ─────────────────────────────────────────────────────────
// Minimal wl_surface handler.  CWlSurface already provides:
//   • Destroy() — marshals wl_surface.destroy then calls wl_proxy_destroy,
// so WlPtr<WlSurfaceHandler>::Reset() is protocol-correct.
//   • Default no-op overrides for entrance / leave / preferred_buffer_*.
// Nothing to override for this example.

class WlSurfaceHandler : public wayland::client::CWlSurface<WlSurfaceHandler> {
};

// ══════════════════════════════════════════════════════════════════════════════
// App class
// ══════════════════════════════════════════════════════════════════════════════

class App {
 public:
  int Run();
  ~App();

  // ── Callbacks invoked by the CRTP handlers ──────────────────────────────
  void OnXdgSurfaceConfigure(uint32_t serial);
  void OnToplevelConfigure(int32_t w, int32_t h);
  void OnToplevelClose();
  void OnSeatCapabilities(uint32_t caps);
  void OnKey(uint32_t key, uint32_t state);
  /// Called by WlCallbackHandler::OnDone — render one frame and arm the next
  /// frame callback.
  void OnFrameReady(uint32_t time_ms) noexcept;

 private:
  // ── Member declaration order determines RAII destruction order.
  //    Declared first → destroyed last; declared last → destroyed first.
  //
  //    Destruction sequence (reverse of declaration order):
  //      frame_callback_ → keyboard_ → seat_ → xdg_toplevel_ → xdg_surface_ →
  //      xdg_wm_base_ → egl_ → surface_ → compositor_ → registry_ → display_

  // Wayland display — destroyed last so all proxy operations remain valid.
  struct DisplayRaii {
    wl_display* d = nullptr;
    ~DisplayRaii() noexcept {
      if (d)
        wl_display_disconnect(d);
    }
  } display_;

  // Registry — destroyed before display_.
  wl::CRegistry registry_;

  // wl_compositor — destroyed before registry_.  wl_compositor has no
  // protocol destroy request; WlPtr::Reset() calls wl_proxy_destroy directly.
  wl::WlPtr<WlCompositorHandler> compositor_;

  // wl_surface — destroyed before compositor_.  CWlSurface::Destroy() sends
  // wl_surface.destroy then wl_proxy_destroy, so the protocol is satisfied
  // automatically when WlPtr<WlSurfaceHandler>::Reset() fires.
  wl::WlPtr<WlSurfaceHandler> surface_;

  // EGL state — declared after surface_ so its destructor runs before
  // surface_'s, tearing down the EGL window before the wl_surface proxy.
  struct EglState {
    EGLDisplay display = EGL_NO_DISPLAY;
    EGLContext context = EGL_NO_CONTEXT;
    EGLSurface surface = EGL_NO_SURFACE;
    EGLConfig config = {};
    wl_egl_window* window = nullptr;

    ~EglState() noexcept {
      if (display == EGL_NO_DISPLAY)
        return;
      eglMakeCurrent(display, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
      if (surface != EGL_NO_SURFACE)
        eglDestroySurface(display, surface);
      if (context != EGL_NO_CONTEXT)
        eglDestroyContext(display, context);
      if (window)
        wl_egl_window_destroy(window);
      eglTerminate(display);
    }
    EglState() = default;
    EglState(const EglState&) = delete;
    EglState& operator=(const EglState&) = delete;
  } egl_;

  // CRTP handlers — destroyed in reverse: toplevel first, wm_base last.
  wl::WlPtr<XdgWmBaseHandler> xdg_wm_base_;
  wl::WlPtr<XdgSurfaceHandler> xdg_surface_;
  wl::WlPtr<XdgToplevelHandler> xdg_toplevel_;
  wl::WlPtr<WlSeatHandler> seat_;
  wl::WlPtr<WlKeyboardHandler> keyboard_;
  // Frame-pacing callback — destroyed first among all WlPtrs.
  wl::WlPtr<WlCallbackHandler> frame_callback_;

  // Application state
  bool running_ = true;
  bool configured_ = false;
  int width_ = 800;
  int height_ = 600;
  uint64_t frame_ = 0;

  // Globals recorded during registry scan
  uint32_t compositor_name_ = 0, compositor_ver_ = 0;
  uint32_t xdg_wm_base_name_ = 0, xdg_wm_base_ver_ = 0;
  uint32_t seat_name_ = 0, seat_ver_ = 0;

  /// Maximum time (ms) to wait for a compositor response during startup.
  static constexpr int kRoundtripTimeoutMs = 5000;

  // ── Internal pipeline steps ─────────────────────────────────────────────
  bool ConnectDisplay();
  bool ScanGlobals();
  bool BindGlobals();
  bool CreateSurfaces();
  bool InitEgl();
  /// Run the render loop.  Returns true on a clean exit (user closed window or
  /// pressed ESC), false if the compositor disconnected unexpectedly.
  bool MainLoop();
  // (No CleanupEgl — EglState::~EglState() handles teardown automatically.)

  /// Timeout-aware replacement for wl_display_roundtrip().
  [[nodiscard]] bool RoundtripWithTimeout(
      int timeout_ms = kRoundtripTimeoutMs) const noexcept;

  /// Register a wl_surface.frame callback with the compositor.
  void RequestFrameCallback() noexcept;

  /// Render one frame (GL clear + colour cycle) and swap buffers.
  void RenderFrame() noexcept;

  // ── Protocol teardown helpers ────────────────────────────────────────────
  /// Send wl_keyboard.release (seat v≥3), then destroy the proxy.
  void ReleaseKeyboard() noexcept;
  /// Send wl_seat.release (seat v≥5), then destroy the proxy.
  void ReleaseSeat() noexcept;

  // ── Template helpers ─────────────────────────────────────────────────────

  /// Attach @p raw to a WlPtr handler, install its event listener, and wire
  /// the back-pointer.  Returns false (and does nothing) if @p raw is null.
  template <typename Handler>
  [[nodiscard]] bool SetupHandler(wl::WlPtr<Handler>& ptr,
                                  wl_proxy* raw) noexcept {
    if (!raw)
      return false;
    ptr.Get()->app_ = this;
    ptr.Get()->_SetProxy(raw);
    return true;
  }

  /// Bind a registry global capped to the version the traits were compiled
  /// against, then set up the CRTP handler.  Returns false on failure.
  template <typename Traits, typename Handler>
  [[nodiscard]] bool BindHandler(wl::WlPtr<Handler>& ptr,
                                 const uint32_t name,
                                 uint32_t ver) noexcept {
    return SetupHandler(
        ptr, registry_.Bind<Traits>(name, std::min(ver, Traits::version)));
  }
};

// ══════════════════════════════════════════════════════════════════════════════
// Handler method implementations (need full App definition)
// ══════════════════════════════════════════════════════════════════════════════

void XdgSurfaceHandler::OnConfigure(const uint32_t serial) {
  AckConfigure(serial);
  app_->OnXdgSurfaceConfigure(serial);
}

void XdgToplevelHandler::OnConfigure(const int32_t w,
                                     const int32_t h,
                                     wl_array* /*states*/) {
  app_->OnToplevelConfigure(w, h);
}

void XdgToplevelHandler::OnClose() {
  app_->OnToplevelClose();
}

void WlSeatHandler::OnCapabilities(const uint32_t caps) {
  app_->OnSeatCapabilities(caps);
}

void WlKeyboardHandler::OnKey(uint32_t /*serial*/,
                              uint32_t /*time*/,
                              const uint32_t key,
                              const uint32_t state) {
  app_->OnKey(key, state);
}

void WlCallbackHandler::OnDone(const uint32_t time_ms) {
  app_->OnFrameReady(time_ms);
}

// ══════════════════════════════════════════════════════════════════════════════
// App method implementations
// ══════════════════════════════════════════════════════════════════════════════

App::~App() {
  // Send versioned protocol release requests before member destructors run.
  // These are conditional on the seat version and cannot be expressed purely
  // through WlPtr::Reset(), so they remain as explicit teardown steps.
  ReleaseKeyboard();  // wl_keyboard.release (seat v≥3), then WlPtr::Reset()
                      // no-ops
  ReleaseSeat();      // wl_seat.release (seat v≥5), then WlPtr::Reset() no-ops

  // Everything else is handled by member destructors in declaration-reverse
  // order:
  //   frame_callback_ → keyboard_ → seat_ → xdg_toplevel_ → xdg_surface_ →
  //   xdg_wm_base_ → egl_ (EglState dtor) → surface_ (wl_surface.destroy) →
  //   compositor_ (wl_proxy_destroy) → registry_ → display_ (disconnect).
}

int App::Run() {
  if (!ConnectDisplay())
    return EXIT_FAILURE;
  if (!ScanGlobals())
    return EXIT_FAILURE;
  if (!BindGlobals())
    return EXIT_FAILURE;
  if (!CreateSurfaces())
    return EXIT_FAILURE;
  if (!InitEgl())
    return EXIT_FAILURE;
  return MainLoop() ? EXIT_SUCCESS : EXIT_FAILURE;
}

// ── ConnectDisplay
// ────────────────────────────────────────────────────────────

bool App::ConnectDisplay() {
  display_.d = wl_display_connect(nullptr);
  if (!display_.d) {
    std::fprintf(stderr, "simple-egl: wl_display_connect: %s\n",
                 std::strerror(errno));
    return false;
  }
  return true;
}

// ── RoundtripWithTimeout
// ──────────────────────────────────────────────────────

bool App::RoundtripWithTimeout(const int timeout_ms) const noexcept {
  // wl_display_sync creates a server-side sync marker.  The compositor fires
  // wl_callback.done when all requests queued before the sync have been
  // processed.  We use poll() around each blocking read, so we never wait
  // longer than timeout_ms milliseconds for an unresponsive compositor.
  bool sync_done = false;

  wl_callback* const sync_cb = wl_display_sync(display_.d);
  if (!sync_cb)
    return false;

  // ScopeExit guarantees wl_callback_destroy on every return path — success,
  // timeout, and I/O error alike — without duplicated cleanup calls.
  const auto guard = wl::ScopeExit{[sync_cb] { wl_callback_destroy(sync_cb); }};

  // Stateless lambda converts to a plain C function pointer (C++11 §5.1.2).
  static constexpr wl_callback_listener kSyncListener = {
      [](void* data, wl_callback* /*cb*/, uint32_t /*serial*/) noexcept {
        *static_cast<bool*>(data) = true;
      }};
  wl_callback_add_listener(sync_cb, &kSyncListener, &sync_done);

  const int fd = wl_display_get_fd(display_.d);
  bool ok = true;

  while (!sync_done && ok) {
    // ── Write ──────────────────────────────────────────────────────────────
    // Flush outgoing requests (including the sync) to the compositor.
    if (wl_display_flush(display_.d) < 0) {
      if (errno != EAGAIN) {
        ok = false;
        break;
      }
      // Socket buffer is full; wait for it to drain, then retry the flush.
      pollfd out{fd, POLLOUT, 0};
      if (poll(&out, 1, timeout_ms) <= 0) {
        ok = false;
        break;
      }
      continue;
    }

    // ── Wait ───────────────────────────────────────────────────────────────
    // Block until the compositor sends data or the deadline elapses.
    pollfd in{fd, POLLIN, 0};
    const int n = poll(&in, 1, timeout_ms);
    if (n < 0 && errno == EINTR)
      continue;  // signal — retry
    if (n <= 0) {
      ok = false;
      break;
    }  // 0 = timeout, -1 = I/O error

    // ── Read & dispatch ────────────────────────────────────────────────────
    if (wl_display_dispatch(display_.d) < 0) {
      ok = false;
      break;
    }
  }

  // guard fires here — wl_callback_destroy(sync_cb) called automatically.
  return ok && sync_done;
}

// ── ScanGlobals
// ───────────────────────────────────────────────────────────────

bool App::ScanGlobals() {
  if (!registry_.Create(display_.d)) {
    std::fprintf(stderr, "simple-egl: wl_display_get_registry failed\n");
    return false;
  }

  registry_.OnGlobal([this](wl::CRegistry& /*reg*/, uint32_t name,
                            std::string_view iface, uint32_t ver) {
    using wl_comp = wayland::client::wl_compositor_traits;
    using xdg_base = xdg_shell::client::xdg_wm_base_traits;
    using wl_s = wayland::client::wl_seat_traits;

    if (iface == wl_comp::interface_name) {
      compositor_name_ = name;
      compositor_ver_ = ver;
    } else if (iface == xdg_base::interface_name) {
      xdg_wm_base_name_ = name;
      xdg_wm_base_ver_ = ver;
    } else if (iface == wl_s::interface_name) {
      seat_name_ = name;
      seat_ver_ = ver;
    }
  });

  if (!RoundtripWithTimeout()) {
    std::fprintf(stderr,
                 "simple-egl: timed out waiting for global advertisements\n");
    return false;
  }

  if (!compositor_name_) {
    std::fprintf(stderr, "simple-egl: wl_compositor not advertised\n");
    return false;
  }
  if (!xdg_wm_base_name_) {
    std::fprintf(stderr, "simple-egl: xdg_wm_base not advertised\n");
    return false;
  }
  return true;
}

// ── BindGlobals
// ───────────────────────────────────────────────────────────────

bool App::BindGlobals() {
  using namespace wayland::client;
  using namespace xdg_shell::client;

  // wl_compositor — no events, so use Attach() rather than BindHandler() to
  // skip listener installation (CWlCompositor has no s_listener_table_).
  if (wl_proxy* raw = registry_.Bind<wl_compositor_traits>(
          compositor_name_,
          std::min(compositor_ver_, wl_compositor_traits::version))) {
    compositor_.Attach(raw);
  } else {
    std::fprintf(stderr, "simple-egl: wl_compositor bind failed\n");
    return false;
  }

  // xdg_wm_base — CRTP handler receives ping events
  if (!BindHandler<xdg_wm_base_traits>(xdg_wm_base_, xdg_wm_base_name_,
                                       xdg_wm_base_ver_)) {
    std::fprintf(stderr, "simple-egl: xdg_wm_base bind failed\n");
    return false;
  }

  // wl_seat — optional; skip silently if not advertised
  if (seat_name_)
    std::ignore = BindHandler<wl_seat_traits>(seat_, seat_name_, seat_ver_);

  // Roundtrip so seat capabilities arrive before CreateSurfaces.
  if (!RoundtripWithTimeout()) {
    std::fprintf(stderr,
                 "simple-egl: timed out waiting for seat capabilities\n");
    return false;
  }
  return true;
}

// ── CreateSurfaces
// ────────────────────────────────────────────────────────────

bool App::CreateSurfaces() {
  using namespace wayland::client;
  using namespace xdg_shell::client;

  // wl_compositor.create_surface → wl_surface.
  // wl::construct<> encodes the child interface and opcode at compile time,
  // replacing the raw wl_proxy_marshal_constructor call.
  if (wl_proxy* raw = wl::construct<wl_surface_traits,
                                    wl_compositor_traits::Op::CreateSurface>(
          *compositor_.Get())) {
    surface_.Get()->_SetProxy(raw);
  } else {
    std::fprintf(stderr, "simple-egl: wl_compositor.create_surface failed\n");
    return false;
  }

  // xdg_wm_base.get_xdg_surface → xdg_surface.
  if (!SetupHandler(xdg_surface_,
                    wl::construct<xdg_surface_traits,
                                  xdg_wm_base_traits::Op::GetXdgSurface>(
                        *xdg_wm_base_.Get(), surface_.Get()->GetProxy()))) {
    std::fprintf(stderr, "simple-egl: xdg_wm_base.get_xdg_surface failed\n");
    return false;
  }

  // xdg_surface.get_toplevel → xdg_toplevel.
  if (!SetupHandler(xdg_toplevel_,
                    wl::construct<xdg_toplevel_traits,
                                  xdg_surface_traits::Op::GetToplevel>(
                        *xdg_surface_.Get()))) {
    std::fprintf(stderr, "simple-egl: xdg_surface.get_toplevel failed\n");
    return false;
  }

  xdg_toplevel_.Get()->SetTitle("simple-egl");
  xdg_toplevel_.Get()->SetAppId("org.wayland-cxx.simple-egl");

  surface_.Get()->Commit();
  if (!RoundtripWithTimeout()) {
    std::fprintf(stderr,
                 "simple-egl: timed out waiting for xdg_surface configure\n");
    return false;
  }
  return true;
}

// ── InitEgl
// ───────────────────────────────────────────────────────────────────

bool App::InitEgl() {
  egl_.display = eglGetDisplay(
      // NOLINTNEXTLINE(cppcoreguidelines-pro-type-cstyle-cast)
      static_cast<EGLNativeDisplayType>(display_.d));
  if (egl_.display == EGL_NO_DISPLAY) {
    std::fprintf(stderr, "simple-egl: eglGetDisplay failed\n");
    return false;
  }

  EGLint major = 0, minor = 0;
  if (!eglInitialize(egl_.display, &major, &minor)) {
    std::fprintf(stderr, "simple-egl: eglInitialize failed\n");
    return false;
  }
  std::printf("simple-egl: EGL %d.%d initialised\n", major, minor);

  if (!eglBindAPI(EGL_OPENGL_ES_API)) {
    std::fprintf(stderr, "simple-egl: eglBindAPI(OPENGL_ES) failed\n");
    return false;
  }

  // NOLINTBEGIN(cppcoreguidelines-avoid-c-arrays)
  static const EGLint kConfigAttribs[] = {
      EGL_SURFACE_TYPE,
      EGL_WINDOW_BIT,
      EGL_RENDERABLE_TYPE,
      EGL_OPENGL_ES2_BIT,
      EGL_RED_SIZE,
      8,
      EGL_GREEN_SIZE,
      8,
      EGL_BLUE_SIZE,
      8,
      EGL_ALPHA_SIZE,
      8,
      EGL_DEPTH_SIZE,
      24,
      EGL_NONE,
  };
  // NOLINTEND(cppcoreguidelines-avoid-c-arrays)

  EGLint num_configs = 0;
  if (!eglChooseConfig(egl_.display, std::data(kConfigAttribs), &egl_.config, 1,
                       &num_configs) ||
      num_configs < 1) {
    std::fprintf(stderr, "simple-egl: eglChooseConfig failed\n");
    return false;
  }

  // NOLINTBEGIN(cppcoreguidelines-avoid-c-arrays)
  static constexpr EGLint kCtxAttribs[] = {EGL_CONTEXT_CLIENT_VERSION, 2,
                                           EGL_NONE};
  // NOLINTEND(cppcoreguidelines-avoid-c-arrays)
  egl_.context = eglCreateContext(egl_.display, egl_.config, EGL_NO_CONTEXT,
                                  std::data(kCtxAttribs));
  if (egl_.context == EGL_NO_CONTEXT) {
    std::fprintf(stderr, "simple-egl: eglCreateContext failed\n");
    return false;
  }

  egl_.window = wl_egl_window_create(
      // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
      reinterpret_cast<wl_surface*>(surface_.Get()->GetProxy()), width_,
      height_);
  if (!egl_.window) {
    std::fprintf(stderr, "simple-egl: wl_egl_window_create failed\n");
    return false;
  }

  egl_.surface = eglCreateWindowSurface(
      egl_.display, egl_.config,
      // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
      reinterpret_cast<EGLNativeWindowType>(egl_.window), nullptr);
  if (egl_.surface == EGL_NO_SURFACE) {
    std::fprintf(stderr, "simple-egl: eglCreateWindowSurface failed\n");
    return false;
  }

  if (!eglMakeCurrent(egl_.display, egl_.surface, egl_.surface, egl_.context)) {
    std::fprintf(stderr, "simple-egl: eglMakeCurrent failed\n");
    return false;
  }

  // Request vsync (swap interval 1).  Default is implementation-defined;
  // some EGL platforms default to 0 (unconstrained), causing a busy-loop.
  eglSwapInterval(egl_.display, 1);

  return true;
}

// ── MainLoop
// ──────────────────────────────────────────────────────────────────

/// Log the reason for a Wayland display error.
///
/// wl_display_get_error() returns an errno-compatible code:
///   • EPROTO  → the compositor sent a bad protocol message; use
///               wl_display_get_protocol_error() for the exact code.
///   • anything else → a plain I/O error (EPIPE, ECONNRESET, …).
static void LogWlError(wl_display* display, const char* context) noexcept {
  const int err = wl_display_get_error(display);
  const int code = err ? err : errno;
  if (code == EPROTO) {
    const wl_interface* iface = nullptr;
    uint32_t obj_id = 0;
    const uint32_t proto_code =
        wl_display_get_protocol_error(display, &iface, &obj_id);
    std::fprintf(stderr,
                 "simple-egl: compositor protocol error (%s): code %u"
                 " on %s object %u\n",
                 context, proto_code, iface ? iface->name : "unknown", obj_id);
  } else {
    std::fprintf(stderr,
                 "simple-egl: compositor disconnected (%s): %s\n",
                 context, std::strerror(code));
  }
}

bool App::MainLoop() {
  std::printf("simple-egl: entering render loop (ESC or close to quit)\n");

  // Kickstart: arm the first frame callback, then render and commit frame 0.
  // The compositor will reply with wl_callback.done when it is ready for
  // frame 1, at which point OnFrameReady() takes over the callback chain.
  RequestFrameCallback();
  RenderFrame();  // eglSwapBuffers commits the buffer + the callback request

  const int fd = wl_display_get_fd(display_.d);

  while (running_) {
    // ── Write phase ──────────────────────────────────────────────────────────
    // Flush all outgoing protocol messages (frame-callback requests, acks…).
    // If the compositor socket is temporarily full, poll for writeability
    // instead of spinning.
    while (wl_display_flush(display_.d) < 0) {
      if (errno != EAGAIN) {
        LogWlError(display_.d, "flush");
        return false;
      }
      pollfd pfd{fd, POLLOUT, 0};
      if (poll(&pfd, 1, -1) < 0) {
        if (errno == EINTR)
          continue;
        std::fprintf(stderr, "simple-egl: poll(POLLOUT) failed: %s\n",
                     std::strerror(errno));
        return false;
      }
    }

    // ── Dispatch phase ───────────────────────────────────────────────────────
    // Dispatch events already in the client-side queue (no blocking).
    if (wl_display_dispatch_pending(display_.d) < 0) {
      LogWlError(display_.d, "dispatch_pending");
      return false;
    }

    // ── Wait phase ───────────────────────────────────────────────────────────
    // Block until the compositor sends at least one event (frame done,
    // configure, keyboard input, …).
    pollfd pfd{fd, POLLIN, 0};
    if (poll(&pfd, 1, -1) < 0) {
      if (errno == EINTR)
        continue;
      std::fprintf(stderr, "simple-egl: poll(POLLIN) failed: %s\n",
                   std::strerror(errno));
      return false;
    }

    // Read and dispatch the incoming event(s).
    if (wl_display_dispatch(display_.d) < 0) {
      LogWlError(display_.d, "dispatch");
      return false;
    }
  }

  std::printf("simple-egl: exiting cleanly\n");
  return true;
}

void App::RenderFrame() noexcept {
  const float r = static_cast<float>(frame_ % 256u) / 255.0f;
  glClearColor(r, 0.3f, 0.5f, 1.0f);
  glClear(GL_COLOR_BUFFER_BIT);
  eglSwapBuffers(egl_.display, egl_.surface);
  ++frame_;
}

void App::ReleaseKeyboard() noexcept {
  if (keyboard_.IsNull())
    return;
  // wl_keyboard.release is a destructor request available since seat version 3.
  // It sends the protocol message and destroys the proxy internally.
  // For older seats (v1/v2), fall through to Reset() which just calls
  // wl_proxy_destroy without a protocol message (correct for those versions).
  using Kbd = wayland::client::wl_keyboard_traits;
  if (seat_ver_ >= Kbd::Op::Since::Release)
    keyboard_.Get()
        ->Release();  // marshals release + calls wl_proxy_destroy internally
  keyboard_.Reset();  // no-op if Release() already detached the proxy
}

void App::ReleaseSeat() noexcept {
  if (seat_.IsNull())
    return;
  // wl_seat.release is a destructor request available since seat version 5.
  using S = wayland::client::wl_seat_traits;
  if (seat_ver_ >= S::Op::Since::Release)
    seat_.Get()
        ->Release();  // marshals release + calls wl_proxy_destroy internally
  seat_.Reset();      // no-op if Release() already detached the proxy
}

// ── Frame-callback helpers
// ────────────────────────────────────────────────────

void App::RequestFrameCallback() noexcept {
  // wl_surface.frame → wl_callback.  wl::construct<> encodes the child
  // interface and opcode at compile time; the request must arrive before the
  // corresponding wl_surface.commit (implicit in eglSwapBuffers) so that both
  // land in the same compositor message batch.
  using wl_s = wayland::client::wl_surface_traits;
  using wl_c = wayland::client::wl_callback_traits;
  if (wl_proxy* raw = wl::construct<wl_c, wl_s::Op::Frame>(*surface_.Get())) {
    frame_callback_.Get()->app_ = this;
    frame_callback_.Get()->_SetProxy(raw);
  }
}

void App::OnFrameReady(uint32_t /*time_ms*/) noexcept {
  // The compositor has presented the previous frame and is ready for the next.

  // Detach the now-spent wl_callback proxy before arming the next one.
  // Detach() sets m_proxy to nullptr without calling wl_proxy_destroy, so
  // the proxy stays alive through the rest of this dispatch cycle.
  wl_proxy* const spent_cb = frame_callback_.Detach();
  // ScopeExit guarantees wl_proxy_destroy is called on all paths — including
  // any early return added in the future — without an explicit if-destroy at
  // the bottom of the function.
  const auto guard = wl::ScopeExit{[spent_cb] {
    if (spent_cb)
      wl_proxy_destroy(spent_cb);
  }};

  // Arm the next frame callback BEFORE the buffer commit, so the request and
  // commit are delivered to the compositor in the same message batch.
  RequestFrameCallback();

  // Render and commit frame N+1.
  RenderFrame();
}

// ── App callbacks
// ─────────────────────────────────────────────────────────────

void App::OnXdgSurfaceConfigure(uint32_t /*serial*/) {
  configured_ = true;
}

void App::OnToplevelConfigure(const int32_t w, const int32_t h) {
  // Clamp to a sane upper bound; a compositor bug or malicious value of
  // INT32_MAX would otherwise be forwarded directly to wl_egl_window_resize.
  static constexpr int32_t kMaxDim = 16384;
  if (w > 0 && h > 0) {
    width_ = std::min(w, kMaxDim);
    height_ = std::min(h, kMaxDim);
    if (egl_.window)
      wl_egl_window_resize(egl_.window, width_, height_, 0, 0);
  }
}

void App::OnToplevelClose() {
  running_ = false;
}

void App::OnSeatCapabilities(const uint32_t caps) {
  if (const bool has_kbd = (caps & WL_SEAT_CAPABILITY_KEYBOARD) != 0u;
      has_kbd && keyboard_.IsNull()) {
    using wl_s = wayland::client::wl_seat_traits;
    using wl_k = wayland::client::wl_keyboard_traits;
    if (auto* raw = wl::construct<wl_k, wl_s::Op::GetKeyboard>(*seat_.Get())) {
      keyboard_.Get()->app_ = this;
      keyboard_.Get()->_SetProxy(raw);
    }
  } else if (!has_kbd && !keyboard_.IsNull()) {
    ReleaseKeyboard();
  }
}

void App::OnKey(const uint32_t key, const uint32_t state) {
  if (key == KEY_ESC && state == WL_KEYBOARD_KEY_STATE_PRESSED)
    running_ = false;
}

// ══════════════════════════════════════════════════════════════════════════════
// Entry point
// ══════════════════════════════════════════════════════════════════════════════

int main() {
  // Suppress SIGPIPE so that a compositor disconnect during wl_display_flush
  // is reported as EPIPE / error return rather than terminating the process.
  std::signal(SIGPIPE, SIG_IGN);

  App app;
  return app.Run();
}
